---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: prescriptions-refresh-pypi
spec:
  templates:
    - name: pypi-artifact-size
      resubmitPendingPods: true
      container:
        name: pypi-artifact-size
        image: prescriptions-refresh-job
        env:
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
          - name: GIT_SSH_COMMAND
            # Needed to keep weak host verification for git clone.
            value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: deployment-name
          - name: APP_SCRIPT
            value: app.sh
          - name: THOTH_PRESCRIPTIONS_REFRESH_SUBCOMMAND
            value: pypi-artifact-size
          - name: GITHUB_PRIVATE_KEY_PATH
            value: /opt/app-root/src/.github/github-privatekey
          - name: THOTH_LOGGING_NO_JSON
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: logging-no-json
          - name: THOTH_PRESCRIPTIONS_REFRESH_GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: kebechet
                key: github-oauth-token
          - name: GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                name: kebechet
                key: GITHUB_APP_ID
          - name: THOTH_PRESCRIPTIONS_REFRESH_GITHUB_LABELS
            value: bot
          - name: THOTH_PRESCRIPTIONS_REFRESH_REPO
            value: git@github.com:thoth-station/prescriptions.git
          - name: THOTH_PRESCRIPTIONS_REFRESH_DEBUG
            value: "1"
          - name: PROMETHEUS_PUSHGATEWAY_HOST
            valueFrom:
              configMapKeyRef:
                key: pushgateway-host
                name: prometheus
          - name: PROMETHEUS_PUSHGATEWAY_PORT
            valueFrom:
              configMapKeyRef:
                key: pushgateway-port
                name: prometheus
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: ssh-config
            mountPath: /opt/app-root/src/.ssh
          - name: github-app-privatekey
            mountPath: /opt/app-root/src/.github/
            readOnly: true
    - name: pypi-downloads
      resubmitPendingPods: true
      container:
        name: pypi-downloads
        image: prescriptions-refresh-job
        env:
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
          - name: GIT_SSH_COMMAND
            # Needed to keep weak host verification for git clone.
            value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: deployment-name
          - name: APP_SCRIPT
            value: app.sh
          - name: THOTH_PRESCRIPTIONS_REFRESH_SUBCOMMAND
            value: pypi-downloads
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: prescriptions
                key: aicoe-thoth-ops-b9fa132d5b9a.json
          - name: GITHUB_PRIVATE_KEY_PATH
            value: /opt/app-root/src/.github/github-privatekey
          - name: THOTH_LOGGING_NO_JSON
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: logging-no-json
          - name: THOTH_PRESCRIPTIONS_REFRESH_GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: kebechet
                key: github-oauth-token
          - name: GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                name: kebechet
                key: GITHUB_APP_ID
          - name: THOTH_PRESCRIPTIONS_REFRESH_GITHUB_LABELS
            value: bot
          - name: THOTH_PRESCRIPTIONS_REFRESH_REPO
            value: git@github.com:thoth-station/prescriptions.git
          - name: THOTH_PRESCRIPTIONS_REFRESH_DEBUG
            value: "1"
          - name: PROMETHEUS_PUSHGATEWAY_HOST
            valueFrom:
              configMapKeyRef:
                key: pushgateway-host
                name: prometheus
          - name: PROMETHEUS_PUSHGATEWAY_PORT
            valueFrom:
              configMapKeyRef:
                key: pushgateway-port
                name: prometheus
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
          - name: ssh-config
            mountPath: /opt/app-root/src/.ssh
          - name: github-app-privatekey
            mountPath: /opt/app-root/src/.github/
            readOnly: true
    - name: pypi-maintainers
      resubmitPendingPods: true
      container:
        name: pypi-maintainers
        image: prescriptions-refresh-job
        env:
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
          - name: GIT_SSH_COMMAND
            # Needed to keep weak host verification for git clone.
            value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: deployment-name
          - name: APP_SCRIPT
            value: app.sh
          - name: THOTH_PRESCRIPTIONS_REFRESH_SUBCOMMAND
            value: pypi-maintainers
          - name: GITHUB_PRIVATE_KEY_PATH
            value: /opt/app-root/src/.github/github-privatekey
          - name: THOTH_LOGGING_NO_JSON
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: logging-no-json
          - name: THOTH_PRESCRIPTIONS_REFRESH_GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: kebechet
                key: github-oauth-token
          - name: GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                name: kebechet
                key: GITHUB_APP_ID
          - name: THOTH_PRESCRIPTIONS_REFRESH_GITHUB_LABELS
            value: bot
          - name: THOTH_PRESCRIPTIONS_REFRESH_REPO
            value: git@github.com:thoth-station/prescriptions.git
          - name: THOTH_PRESCRIPTIONS_REFRESH_DEBUG
            value: "1"
          - name: PROMETHEUS_PUSHGATEWAY_HOST
            valueFrom:
              configMapKeyRef:
                key: pushgateway-host
                name: prometheus
          - name: PROMETHEUS_PUSHGATEWAY_PORT
            valueFrom:
              configMapKeyRef:
                key: pushgateway-port
                name: prometheus
        resources:
          limits:
            cpu: 500m
            memory: 384Mi
          requests:
            cpu: 500m
            memory: 384Mi
        volumeMounts:
          - name: ssh-config
            mountPath: /opt/app-root/src/.ssh
          - name: github-app-privatekey
            mountPath: /opt/app-root/src/.github/
            readOnly: true
    - name: pypi-release
      resubmitPendingPods: true
      container:
        name: pypi-release
        image: prescriptions-refresh-job
        env:
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
          - name: GIT_SSH_COMMAND
            # Needed to keep weak host verification for git clone.
            value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: deployment-name
          - name: APP_SCRIPT
            value: app.sh
          - name: THOTH_PRESCRIPTIONS_REFRESH_SUBCOMMAND
            value: pypi-release
          - name: GITHUB_PRIVATE_KEY_PATH
            value: /opt/app-root/src/.github/github-privatekey
          - name: THOTH_LOGGING_NO_JSON
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: logging-no-json
          - name: THOTH_PRESCRIPTIONS_REFRESH_GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: kebechet
                key: github-oauth-token
          - name: GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                name: kebechet
                key: GITHUB_APP_ID
          - name: THOTH_PRESCRIPTIONS_REFRESH_GITHUB_LABELS
            value: bot
          - name: THOTH_PRESCRIPTIONS_REFRESH_REPO
            value: git@github.com:thoth-station/prescriptions.git
          - name: THOTH_PRESCRIPTIONS_REFRESH_DEBUG
            value: "1"
          - name: PROMETHEUS_PUSHGATEWAY_HOST
            valueFrom:
              configMapKeyRef:
                key: pushgateway-host
                name: prometheus
          - name: PROMETHEUS_PUSHGATEWAY_PORT
            valueFrom:
              configMapKeyRef:
                key: pushgateway-port
                name: prometheus
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: ssh-config
            mountPath: /opt/app-root/src/.ssh
          - name: github-app-privatekey
            mountPath: /opt/app-root/src/.github/
            readOnly: true
