---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mi-scheduler
data:
  entities: "PullRequest, Issue"
  repositories: "openshift/origin"
  organizations: "thoth-station,AICoE,aicoe-aiops"
  parallel-workflows-limit: "1"
