kind: Route
apiVersion: route.openshift.io/v1
metadata:
    name: pulp-external
    annotations:
        kubernetes.io/tls-acme: "true"
spec:
    host: pulp.operate-first.cloud
    to:
        kind: Service
        name: example-pulp-api-svc
        weight: 100
    port:
        targetPort: api-24817
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
    name: pulp-content-external
    annotations:
        kubernetes.io/tls-acme: "true"
spec:
    host: pulp-content.operate-first.cloud
    to:
        kind: Service
        name: example-pulp-content-svc
        weight: 100
    port:
        targetPort: content-24816
