---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: user-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-api
subjects:
  - kind: ServiceAccount
    name: user-api
