apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - role-binding.yaml
  - thoth-notification.yaml
images:
  - name: mi-scheduler
    newName: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/mi-scheduler
    newTag: latest
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: ""
      version: v1
      kind: ConfigMap
      name: mi-scheduler
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: "rbac.authorization.k8s.io"
      version: v1
      kind: Role
      name: mi-scheduler
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: "template.openshift.io"
      version: v1
      kind: Template
      name: mi-merge
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: "template.openshift.io"
      version: v1
      kind: Template
      name: mi
  - patch: |-
      - op: replace
        path: /spec/templates/1/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/mi:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      annotationSelector: "operation=mi"
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
