apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: thoth
  component: slo-reporter
resources:
  - ../../base
  - configmap.yaml
  - thoth-notification.yaml
images:
  - name: slo-reporter
    newName: image-registry.openshift-image-registry.svc:5000/thoth-infra-stage/slo-reporter
    newTag: latest
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - patch: |-
      - op: add
        path: "/spec/jobTemplate/spec/template/spec/containers/0/env/-1"
        value: {"name": "THOTH_SLO_REPORTER_USING_SMTP_TLS", "value": "0"}
    target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: slo-reporter
  - patch: |-
      - op: add
        path: "/spec/jobTemplate/spec/template/spec/containers/0/env/-1"
        value: {"name": "THOTH_SLO_REPORTER_SEND_EMAIL", "value": "1"}
    target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: slo-reporter
