apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - imagestream.yaml
commonLabels:
  app: thoth
  component: document-sync
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
