---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: solver-rhel-8-py36
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: solver-rhel-8-py38
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: solver-fedora-34-py39
spec:
  lookupPolicy:
    local: true
