apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imagestreams.yaml
  - solve_and_sync-template.yaml
  - solver-template.yaml
commonLabels:
  app: thoth
  component: solver
