apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imagestreams.yaml
  - solve_and_sync-template.yaml
  - solver-template.yaml
  - thoth-notification.yaml
patchesJson6902:
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-
commonLabels:
  app: thoth
  component: solver
