apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - thoth-notification.yaml
images:
  - name: pulp-pypi-sync-job
    newName: image-registry.openshift-image-registry.svc:5000/thoth-frontend-stage/pulp-pypi-sync-job
    newTag: latest
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
