apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - role-binding.yaml
  - thoth-notification.yaml
images:
  - name: mi-scheduler
    newName: image-registry.openshift-image-registry.svc:5000/thoth-test-core/mi-scheduler
    newTag: latest
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/templates/1/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-test-core/mi:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      annotationSelector: "operation=mi"
