apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - role-binding.yaml
  - thoth-notification.yaml
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
