---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pulp-metrics-exporter
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/pulp-metrics-exporter:v0.1.0
      importPolicy: {}
      referencePolicy:
        type: Local
