apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - role.yaml
  - role_binding.yaml
  - route.yaml
  - service.yaml
  - thoth-notification.yaml
patchesStrategicMerge:
  - deploymentconfig.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
