---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: user-api-route53
spec:
  host: stage.thoth-station.ninja
  to:
    kind: Service
    name: user-api
  tls:
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
      MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
      DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
      SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
      GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
      AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
      q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
      SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
      Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
      a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
      /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
      AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
      CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
      bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
      c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
      VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
      ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
      MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
      Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
      AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
      uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
      wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
      X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
      PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
      KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
      -----END CERTIFICATE-----
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIFajCCBFKgAwIBAgISBNvyyB+aITFRTYTYjpro6Wu2MA0GCSqGSIb3DQEBCwUA
      MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
      ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDA1MTQwMzAyNDhaFw0y
      MDA4MTIwMzAyNDhaMCQxIjAgBgNVBAMTGXN0YWdlLnRob3RoLXN0YXRpb24ubmlu
      amEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDbW+WqBe8cfzoifYMZ
      ocaqXKHvuU23gimBDujWhOTbt/gNSgEQdfUbHDFMg8KozraXMGK6tvHrUuYsZNMO
      5ycvFDcCLyy13UvuvJixioMMooPo0hcfvd3Y+DNsb1QWGU/CgBRgLoIsII0Otytu
      c17nfJwwCXOLzC9ISz4lM7bsyALlNzrLNV8eOBbUsAPyrGsAMm59U7VCvYXQObIx
      6s3ydy8WWYpC7CcuXygaX7l5LlNHjRNSJtnzRqHKs/M7hvJYBFIH2DjxN/pFrSGL
      tFZjiIuaJ54KWEWELKHtuQUNHfK72qREINMgPjqnZen64bwlNEBHBsgeWg3Qhq1Q
      FDe9AgMBAAGjggJuMIICajAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
      BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFL+e0qhQHJnV
      QVYagVie9uqANMU6MB8GA1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8G
      CCsGAQUFBwEBBGMwYTAuBggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxl
      dHNlbmNyeXB0Lm9yZzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxl
      dHNlbmNyeXB0Lm9yZy8wJAYDVR0RBB0wG4IZc3RhZ2UudGhvdGgtc3RhdGlvbi5u
      aW5qYTBMBgNVHSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEBATAoMCYGCCsG
      AQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQQGCisGAQQB1nkC
      BAIEgfUEgfIA8AB2AOcS8rA3fhpi+47JDGGE8ep7N8tWHREmW/Pg80vyQVRuAAAB
      chFZXiwAAAQDAEcwRQIgIZ9FGbtgB/6KP6NkaP/vtfQtCAsm7cbgojHCRmfqiOkC
      IQDK6OmNn/dwKHaRJ/1A260i6VL8hk+yi2gLCQcKEpYp3gB2AAe3XBvlfWj/8bDG
      HSMVx7rmV3xXlLdq7rxhOhpp06IcAAABchFZXk0AAAQDAEcwRQIhAIRKrCMpc1pY
      QMkg9YehukAzD3RRXiCjgwRoXfW0NVM6AiBZGWSSz5OGaXGoHVen/aREkAoZqMS8
      uLU1UFC/ZRI7KDANBgkqhkiG9w0BAQsFAAOCAQEAR3X9uANyAUXgTli4Y4rmDo0v
      IdiBw+WBSekv3soFR6xMkeQRyrKQsL6Ob4/vBjxV6bhxqNuktyJpJc+V6/VethO9
      6yp1j+tSDInpWyB9+DPKjJqL+OgaVwcT7Sdv0BQ2krnVMxKHJ1K8yTxi4v1mdjEa
      GI+dtXWX7fNvZh6UcYxlZoQ7SGGy87K4EWZUfL07r59AXgkDZSBjqedGE1GPSffP
      p4xUjgWrRmuwcJZRnKcU5DO+57v4/EnYUsb09fZAihCQ8ugKMmhekC65vX7pgjod
      QYOjALF5XL1m0Rqaih/KZWNyY5/kVbe9vfcIdK04ewtmi3bSXpdHTb4ofYLEhQ==
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDbW+WqBe8cfzoi
      fYMZocaqXKHvuU23gimBDujWhOTbt/gNSgEQdfUbHDFMg8KozraXMGK6tvHrUuYs
      ZNMO5ycvFDcCLyy13UvuvJixioMMooPo0hcfvd3Y+DNsb1QWGU/CgBRgLoIsII0O
      tytuc17nfJwwCXOLzC9ISz4lM7bsyALlNzrLNV8eOBbUsAPyrGsAMm59U7VCvYXQ
      ObIx6s3ydy8WWYpC7CcuXygaX7l5LlNHjRNSJtnzRqHKs/M7hvJYBFIH2DjxN/pF
      rSGLtFZjiIuaJ54KWEWELKHtuQUNHfK72qREINMgPjqnZen64bwlNEBHBsgeWg3Q
      hq1QFDe9AgMBAAECggEBANhsbse1WxjundjxpKthZbUn982hMgBgN7rRjwA31eTC
      OcZCwZIQD2hUBH/Nb/1FFflND9vQLBdVjys1vtbxUUOt2igZiy9Ty1scUDq6wllw
      7lyDC7WRipRLLdFKddfn2T25SGEtAdmvs/xU1FEBGx2hYCg06v9+0ReuxP3HbC9n
      whg2M4c0fF20D57x1Pc+F8yE/rF/wZO9gl7nS0hot++h5N7CCzXlOJ9skj0LUKse
      3D5Kmbpw3Ala5lCyXcMtV7gIOug4DDt/+6s1B3nWeriKeoQvUYWjL3jMg+I2qGjk
      9O0eYK0aLzqJ0dF1vkPWGJnfri7U5HBFBVbUSZlaIjECgYEA/9XGPVRGX0TEolLA
      cC0BC9dN1GC6qryMgwsQKW4em/WiWk+pGqlQxjcHE1t2nwgVj7gMCpgmPhEYb/65
      3zfgnyhHupvGg8Th3Rh/LA4/Zdi/vyxp2164p+EIkhnEsua0/cNJ+6sl58VQuroM
      ySePsxtzP3FpaIXN/mbNYidJhRsCgYEA24AaNMK+Zfi1/uBpaMFlsbCwfJEA6uZ7
      a0ZZ8DYTPL1FgdY6sr9wZ2SxD4+Nf0OpxGEnlqKNyHyXou+HC+5yq4is+xCVtGYj
      sXlyPHFhqgZ20NYpPLxcLcRZtrxdDelaqj7Jpc/4Oc6od1i070AZ6IqVkCFxxyW5
      sfYX/snR/AcCgYBUjLbub9quA5EkwEp/CDCPVEGRjcJDSPr7F/3oY09UZbKZPDh7
      6jcauvboq9KhLk/J5p58JdqFqqqz4LBXGCVxFCPYhUDvLXMj2cO1sKO9Kgv8x1XY
      vQ4z1Ug62K9MHLj2IMNjnCVz2p8ahwBQvnVcURcegYG/nHD+wcTgynEevwKBgAj/
      3JMzNNk7dELJ8qhv3XqGkwXYcCAxaPgB/2gA35MK85GaNffkL3idwUCxEw0Xuhsq
      HJRpf8SrjxAIIBJWKW9tACKfEHRAB9Cb+RoPUADHmRGA5lnuIx1hQohierI6UhRO
      1Leuqi+8kF2sTmbMywMkw3MQW/jdTBrGyz8QCUL7AoGARTTWDxSosiYVUSbPGue+
      aq//dDPZkUVJZwWJTrCVIvU8aakiRAlWyTT5nV0A2dnFJpinh6BcjGJ/tXyFqapd
      RpC3IgG9mvYZE4cocztOMn4242GMl4vdR2eFv6fXfGUdw5o2ChSq9RV3agLsOPnH
      kU8DvJ9jm+vSzveBXzRMfxM=
      -----END PRIVATE KEY-----
    termination: edge
