apiVersion: v1
items:
-   apiVersion: v1
    data:
        token: ENC[AES256_GCM,data:rfUG+vUrn8yY0aSeEPRfFf5d059sgmwUOd2G58UmlDnEoZ9PHXnJ6N+iuYVJBxXEla8XFIJNwvlLYIDZvA9UfdnLdKJyJL3T6xOm73gZ9d36ornNHW/CKoclspZrQN0Lb5jJ5yQxDojTxBwGZXfE93ZPIjrRYdkGSvBWTrT0YzouH1mIsnK2/OFPQ/nDLB8Yjup7vCChQyKLayEwlNwOnnhuPQuWt30SOFHdWQmYpvrjWWsh1kkGauuTuPq2C1ct2B5n6Sx745F0TFZ0vs3aqaIlWOxTfNEq6B962ZwV5xnq/efA5z5GIqWgnY5hZRVaBh7pLGrXGfYrkeLPOxF6qBFh3rpew71SMUv/oWp6oZyPuBlwRU9g6XTFa2i6rxd9gChSYxAKUuxg+QcG4GgPRZRXJyuIDUlwMzOookRcc/Fmg0YmE2DCFqTN0CYgWuIXaUxTP9wEwkvanzhm26Ep0rVO7Vy50PLeKA3w7zK+htt4l7WX4czzr4+P+eoP4KqL5qH7akOf8o1rNDNEHsp1nbCehhko/e/KpO80aAp+HSscUL7LQQ/LD1B2kB/mYXYoZWtqW7HhBV5UtKr3SaZ9lRScmYJjOYN4Pcush9vEBuycOkGi4h94zmEstUtvS/L2yRdAMQhHhgEipqmmgyIWivlUIpGG9A9+e0UJxEXbX1yUXtNazSZwlQ4TwCSGF7YvxTP71aK7xBpUiWYahk8In9GFGkSqHf7Adp0pQXU9svjucLlGhwMliQuZ5Q9PfKgzskF5ixNg8vziH7tLyT22xx7e3O77pBPTeL5MpZQEW/pQAA1JAsGHUaXMQYRF8/4r2E8GInE1hdbzZdwaizdxB2ZMnl6yUhRptAMzH1GCyMsGOAUQZPQ2WSPpUyO1Jzdc3AKqsN5d505aDQPBbvmPBXK2X0mqAXzWk3m9QxpSInWyhI0UPKMIHmTWAi+dUshdiJaFXo9v5KieJgNTi/D4hcJQoU+k2hXvPvT1yhl/wEporfxsSdoWqSsLARW0zN8m5yC7I5NoO4NnNIinJAgKhFAG4cK5fQJJ5+nsyoQF8JjSjYDrDtXIzqbdt5ApBiY5Hu4GKVNb2w2ktiOjDRC5Yfe/GL3r9fht3uMjTMFgNWdAtZSbW0S5Wg3tV7eCoxCD4+B3PA2OBIAcHt22ocfOYACPGQU6M76whXcFtulUybSD9oA4Tt8kDrfvz3AKABaX84usJA7VkJXOOxJFGfWAyI/dKiaUPeB6iN80AXO6HSJQb+ug1Z5VIQGs+G8cBIDB5NyZUZ3kbV6wzryusykierLOinUCbaNj2YEUFJf8AczdQSqEBvYm+Lcu9QBJFNpK4XshniCk+iz7D6qPv3rexeKLNRY32EqzhgY8cIOTbn1A4BprDfWAIFjS6oGhISlIosjwskRlHm6ijUXKRKt6/APsFb+Fw3xkPtMEtHdxZ1oLeEm73bZXJNM8DRV+ld59VnBblTOsgmTxCNT4ZbBb/WfFFJ0lkeB+KqzOpXVEl2dffCuiaxTMe9t/z1Fj9a+a8JAinSlnZuzpFkRRPnidXp2eZHtgJFZrW3sKQgXmDmbzM72hKvJMxx+lR9/muAlqU6iN7ZWBvr7LXtSYEpJmL+NnEVFs7M/haxldv4/Paj8Th1xg1ax4KwEsXHkwSUq9JwnVeacS9OEaIwTeE8OdOg4nRJJ6OuE5JuiwgeH5hLl4WIBu7jx2k4ojk8FnC5RcbHA6ANwSN31ghAj6X9nyLC27V/iYcw3Zqbdga4rU2Oo+NgzEgtFeXTGZrIgWqK4z0r+32GUzDn8U26WzuNyLcfcNXWgzwvBqdzDOKnr9+5HAExHkPdZCD66hN2ZNK+/GDtrUaSjgv8tyl//I5vjbv++y7sqEKA6yd9CiTp120sJrniqn5uQq5WCnROi1qx4sYqlHqfr3s1rNenfyeG0QLYqq4HFLasW3YifNUaIxt2f1iS5s7GxCOY+Ixr7EB9QdAj8BqQQG55ZCPru3620GddwmaNJf2+xORrANRb++BIiUvPVpVPuri6wuU502jooqaZvqaZtHURGbL6rL9tlQ5XVOZ6LNG9Mwovf5IpRCA+2dshUgHFGJz/pV6AeBydhuyjKASHz+q7hurIQIXfoeOwqAadXS5sW8LKAX7AYVUaEUxX+QWSV5jad4T5t8GjbGWzTj3D51F7yzIOAdMc1oClcaYKAMlGpJffmZy2hFt9RNEYFDHCqI0bwK07+Mle5gKmJVIKu12CTty9tuoWzX539680GynPJYt32xtqUWX8yFSBow/SK/++Po5TujcBZZcotzqyxmK4vrs5zXB6Asx7wYfuKtL/TE6gsUrBSgOAAyw9kh3XOaPRuI8Qh3gl4Hg/BST1vZdD9dT9XvxNCsOXbZej2rMFs22mATY5POWoJ01f2yiechCI/Dy51+D5ykJcedhs6MnrdDpPukMFA5VEYde9Y=,iv:FWPeN9Fv49YIeMY98VBawPQmF8vzSAqhx4ZG4ekqkvM=,tag:AF9Qk20cPJ3OSDrwPGKv1g==,type:str]
        key-id: ENC[AES256_GCM,data:5+Td7nBBOzwgj27udWIXRljItAmU4vgo1MX1HQ==,iv:vhiJ5YypuNZFMVvbNgvCRnRpVo6OHWACuK9yH+DF3Ck=,tag:GKWrPwsMaFhX2hJ+rQ3QsQ==,type:str]
        secret-key: ENC[AES256_GCM,data:QtfD7CAf5g6FBbWUeutFl9cCWpG4HZ7lcWpuWQSRdmaZQrryS6O4HRvoFvM9e5Cpz+5M8MiSwDg=,iv:XJ2yBzC9NalTl6pg+DB2csYnQIFxvHwGzMQHsdedlzI=,tag:VTAH4DRDZZvb/pDJiVXNvw==,type:str]
    kind: Secret
    metadata:
        name: slo-reporter
    type: Opaque
kind: List
metadata:
    resourceVersion: ""
    selfLink: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-12-01T15:15:46Z'
    mac: ENC[AES256_GCM,data:MRuq4P9XOIE5fJOd5aEt/m+Wjj38jEg+fdlo67Zf6mKMDoFjPZmXBAfq5qA2vvJwnLE6DMp3CXG19Az54WvSfkpqLg1CD9aiHjB+JOTJFPcomryH9oK+9L5z3JBe/PY15WA2Mf1wYERpJ+bwMiusW+mngnrZ4a4Xh1LeELg1LYg=,iv:PUr8HDSC6/cRWlZ8Gmb4USSfxe/Az6XLql8Ja7DVxn4=,tag:vsFlamDqymMniQ8Z9DC72A==,type:str]
    pgp:
    -   created_at: '2021-12-01T15:15:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYAQ/+IeegVdd4wY0ixBjKJKNNcm8NPaZZi0qozYPCwBC1Oty6
            0ZbNW2DKRmYV5SOd5mTsiGQt3PLe1J19f2Z4LPmkb/UVawpEM/9Ot6TCrWjjuNeD
            lLMMLR4LTWDeP1crzD3N+YAlw2iKUS8QTi1K3vOYcGLVhxz/4/1aFuh/6dCMWXjC
            KhpQRyQEwzAJ+3hRvtTkY+ITCjl2hHJT+sMnNZf7E9tmD7m/w0ghe3maGAKFvkN6
            Le8mT+sRhDwKFoOgVIDTGah8o2KEMCPfoAfEyu7Yp6ygdIWbx+4yR1Cx1fbecEtZ
            tN2DFM/XNCl0ouoHadMXL/ZJNMP61qlt9MXFBPICDZTV2k6SG0vlIE367PAE3g7d
            afNYnyJS0GQeXNxihTGO1ZFiOtapjg1FIHLOFKi0j6fRI5upuAKJsfrjU+dGlZwO
            fjawz9nCpZBBP55hKv0VkCElZP6jws1JVFBhej4Q9inW1AlsbE7ryNTnXfuD5DuC
            50GlVI3dGriT9RtT6zsoaNgx2uqJSalzBIPujb+EXHbdgOKq2zXwZO6IrZa/Wy1x
            5Vwe0csoFCS2AtTrSD/LxC9P0t3mmDde8hDiADKaepRuL25PSEepC0DrtO42mWuD
            ee0wUi1MIP6Q3O8Vl2+VLmZ6n1rZfIYmvXUqLU/S10samAM8zSzEWd8k+FVbjTzS
            XgF7MmHLfDz4xXtP5CGFNbp9d2wfVSLLCDM//9137YfCtl4Cao2k7oIGMXOsljOZ
            1+v5o+2mlhZ50Mfnr3YYsEYevurmd5WwZQG3SD9GjTj5CUJ8VDerweDyfx3Wj4M=
            =WxQV
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-12-01T15:15:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf/aHBOYwNDUnrZAV03pYt3TNA1bs8LjhNucemPf/kkj95n
            +FRAfrSGm3Bzw2tM7p3mkq9SdJ1l0SDDeJuwwwfsBXzl1ejB3Yj85kjGHdpkL2Zc
            THeADhy27F2eaWZsDWu6SEsUyx8RUAwO0m4vQK/DfzdWqkTu437+Wa/ifLy7AQcB
            Q7Y3vmEocwgRz/t2hj9ml9QPb7fpf+O8HXEV7AtZrgoOxiuCGWNLzv5sWPNF5jQo
            AJygVirwBX6rhHwYlZVBErjKLIpcOsY4IsncnE1EcnpcAU0+SjymWUlikGG3KiXH
            oGtb0BcJreX0wSOCv3KM2y2yl6co0iP3XdE5EDyr9dJeAVQ9zGATu388U3EIRj1x
            oDmxOYDiA54+YKwb15L7X3mCZ3FrYtt+UuHkU5K1K0IEazesxVrewpCDJyeDSHsX
            evwwcBTOhhC/Xu75XxgKuHtT8bZFTYjE72444TQMIg==
            =ExDh
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-12-01T15:15:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/W3ZCtnv51rIL/cVNMMCLZYctrzfw3ka7ivADZ2ye7A7F
            OHPMMQ9fxGIbdXVNjbxOuL5rMo69tu1LT+qCzPuGQUPW8IdD0Y9AI1bFHvpSiFqo
            HgViiWjOUhhF1BlIcuPHW3uTnYZUbjoo4AaKD7kyQ1/X0YVrsq2OWa6xxh+0XKRI
            Fw0DsZSXd5voIc1vMvqEqUcR1TQYVfgBulv1rSGfOPsERti3OQL/tyxRPiH+dk9w
            GfZuTDBuHLEC3ksNQsIvgtKmiM/4l1G22QVngdd1L3GA6SoAQaGol3mP5Sf93u+X
            Nbp5aYMiyx6e46nW1zuG2JW9L8kwkFVDv7WmqbgwuNJeAYglKetcnGbUYRkFIw0A
            osEPE/VbSK8yNYR5SrjK6UVVxRMDVW5WXNCFkn/sG5oMOpUzor0XtVVIYtIMS/lw
            LrIfkazN222Kyet3i8XPoouQAialOR+K7OVeiwoRCA==
            =huou
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-12-01T15:15:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//dHx+fPYENNqF7pqMC9aDLhrEcij/p2wBmYDA9iQr9Fak
            neLruxPIeB+Xm/usdd7ORSpCe8rwc3saUWMbXDeTpDsrIcqtBglHMVvPrnzikK9h
            ciFZtR80+2XrOfF5jc52e0yFbN93q07JRAWkiGaPrmc+lglmjDZymALPyM/vTnzg
            0zo1M16VAI7JhG8XNUP5QPcaTzdG5Restuhw/yfDcrv/5IuATKTLjLgXrmeVf1dN
            ADqzsM4wDhXGbewoe6Etvr/Q2RJvKhtWXE9t1pk4sSxaE7k53RrblqnI6QurFmyW
            K66gA0/nelVM4lEe5HfSlVgt2CaqgI+wn8g73e8sFLC0OgqjhJz0vPWLsDzSQPcA
            XmJQLnF3VkWIQENtwKhne7PFLxAn3ZQ1b3zzkB6s59A3/RreiYw2DWi7J/Nd8tAh
            zim1ZWvMSie8ITjEXKd/NixVZnfvRaSoSr4rgswDJzo/9EKG1V8qGiXN3x3hYDyk
            bxJj2wYtT8DVvSZ79HKo0MBnedWV0k/D+pt80nw3TY1p9V+Bypbakjr/jL5CujkB
            T7OFxDP7k5qmkuUD67Abt3TWQH/YHB/SiQeQQ8k6hc6A1Ict62W/fy6s/7gYFcrO
            oCgSTLsfzvnKWc0VauIywtrnMz7xuIcEzKneJjs4zV/fHr6tEXaqQu/GaKxSd+/S
            XgEdTRo4hQMIeKXznIkw41dtTA4THnLJrdXAnuOjwbg6DXsCBGJEAs2HipaVZig8
            4susuI53b5swCXUDruTkGI13OGfMKFnzmi5pxuQb7TCbNz0sh9GYGVmrkQDXmkY=
            =9Efl
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    -   created_at: '2021-12-01T15:15:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIOA9LRbhPydJmLEAgAjInj1vBKuV0YTHzivEy6RJv+p7VeZo9h4+Xt5zBEdjnI
            wm9IoON8X8cNb2AYwTWiwKWydhYDdpjWLuTiJLfGxd4y3by2bhPz00+DGSYx5DNy
            ERVoRsLzWOjCwuPdO+wc0hghU0ySHdp+qzQ9G05W2AFVt84c20TYrecfUEZJAAto
            fpyFjQEOzI83q0sD1bvHIx/wuyXUX1Wjm25lElk2c0z3BBxmoa5dV+9yYO0YkIS5
            2nsa7YuzXnTMZ/AUc8sI4rcLmPzCQUADb45m0AQDgaXCnXjXI1HcjClfQj5EeJFw
            9SuezZiKMb7+61MX0ABGnXC7MKsYffV3cOCksCBzJQf+N4erz1x2uj2Ti8yPv/oO
            bnELqbOh13iWF+DGqHYOl3eRrHyjwthRnxBysrCK9wxmFNHvv+Q5W41tuoAwlt1S
            d170XEFl9GUrvB853y1nXNCREZQ4walAYxp8AmYfU9OZD8/2B0fgAgA0Ms2DbXpD
            Gqp/aIfG1JEyfY6O+v/VG+uib0vUr9WeKu+knpBD+OD2PCtSLi7A18H1KANz/mPv
            vgqMNmYA1y4+w4SB3nOO2uj2Qq6/70kPdbV3X+NtUfZigTKxHYRuqtoRTEhAoRCv
            d/roMzJN4iC6VjmPDBJew2PCJngQYIruns4IFoXHa7OyHqRV7jBPHA18tUZtLfb2
            etJeAf3W/JiH61tWYKOSq+5JfiXam6pf08YuAi9aioXxWdy5XFo0xmrqO+0cI4I9
            FP2PNgH5PoSejpMJRoGG9P+npu7TOzjPFcrUSGKePbJLPKrcn5qkxrN5C9X5hgZX
            0w==
            =mgBU
            -----END PGP MESSAGE-----
        fp: 8D191B7544E9CCC3547B25A877E5A5B31D13A647
    -   created_at: '2021-12-01T15:15:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9NBwWNwg7uAAQ/9GDXDLo9v6kbL5IndQi32negSEZwcuCJ2jdjVKZBuroz/
            RrheWSBnJFXz7ZXq0/6WKSehEVbfykOV+GbTVFnfOhx1wr41gVDVwkJmg+eIYkvc
            S46hHFXTq3PCtL3gBRgv0HA1WNUE1z2OHz50Aw/f9/RSGgdD/3zvWDSLiUgN1eW+
            dJLNBIfx2V5WSw1qMDEYI82R6cz9OiaW1eLe+7AyHYoDXHSjF6rgXX1KIZJDRK6l
            2genTFdbIrwR7Zp7WiJJPjejqN8cf/Ip1Viy1q4yULZHuTMr69HD0ePjviO4ytFn
            xNJOYC+HtMQqRfkXN08tZI+ihTuQVHHIZLmh2/hzIXAFsl6dQufKt+lsum102SGt
            0B9voaLMzMIWXx+ZeB4Pl8SUNrSWot/GqXVpoVGzZ8tLdgwl3D4bi8D38qATC1XX
            DDq09FwaFSWMVu6g1cscVY/wKPZ07ARCyKuj7ohqyAMyhh+bWE4nYtpFSD+K2FV7
            OKq4NUFo8i5s53cuOx9q87feZjIccAgJ/3y3JiB7wWvSGTM13aT7Lwyn34hRS4tC
            HIBu9xCiuKYYJodsTTFHLF8sNtbWVH/WTsd2Te4DXZliKsDZ0ulj/aZYAO+/T168
            ZRQea9XG/JV8AfS7HV3jTi2yHJ66vAiQxrx5Lky1RfxkAO5Y+HShiTMp9ApnMx3S
            XgEU8rgPr/86LYbn6F5msppfCg4TBSSxg1W7XPHV2UScWH7xyQInJztyFcGwvUCD
            jJqpe+qgIb810taYyy71LTubnm/wNWVpDKtoJFruRKthpiXLspA1NBvzi4U4f58=
            =K9v8
            -----END PGP MESSAGE-----
        fp: A01778ACB7CC4D41B00FDD78CCBE624D8FF6D016
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
