apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sefkhet-abwy-webhook-receiver
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/sefkhet-abwy-webhook-receiver:v0.3.1
      importPolicy: {}
