apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aicoe-prod-bots
resources:
  - ../../base
  - ultrahook.yaml
patchesStrategicMerge:
  - imagestreamtag.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
