apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
  - thoth-notification.yaml
  - cronjob.yaml
images:
  - name: slo-reporter
    newName: image-registry.openshift-image-registry.svc:5000/aicoe-prod-bots/slo-reporter
    newTag: latest
patchesStrategicMerge:
  - imagestreamtag.yaml
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
