apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - imagestreamtag.yaml
patches:
  - path: resources_patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: solver-any
  - path: put-into-infra-namespace.yaml
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: solver
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-stage/workflow-helpers:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      annotationSelector: "operation=workflow-helpers"
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-stage/"{{inputs.parameters.THOTH_SOLVER_NAME}}":latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: solver-any
