---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: prescriptions-refresh-gh
spec:
  suspend: false
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: prescriptions-refresh-image-analysis
spec:
  suspend: false
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: prescriptions-refresh-pg
spec:
  suspend: false
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: prescriptions-refresh-pypi
spec:
  suspend: false
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: prescriptions-refresh-quay
spec:
  suspend: false
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: prescriptions-refresh-scorecards
spec:
  suspend: true
