apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: thoth
  component: prescriptions-refresh-job
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - imagestreamtag.yaml
  - cronworkflow.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - path: put-into-middletier-namespace.yaml
    target:
      group: template.openshift.io
      version: argoproj.io/v1alpha1
      kind: CronWorkflow
      name: prescriptions-refresh
