apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: thoth
  component: prescriptions-refresh-job
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - configmap.yaml
  - imagestreamtag.yaml
  - cronworkflow.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
      - op: replace
        path: /spec/templates/1/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
      - op: replace
        path: /spec/templates/2/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
      - op: replace
        path: /spec/templates/3/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
      - op: replace
        path: /spec/templates/4/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
      - op: replace
        path: /spec/templates/5/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
      - op: replace
        path: /spec/templates/6/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: prescriptions-refresh-gh
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: prescriptions-refresh-scorecards
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: prescriptions-refresh-pg
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-prod/prescriptions-refresh-job:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name:  prescriptions-refresh-quay
