apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/version: "0.9"
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - imagestreamtag.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-stage/buildlog-parser:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      annotationSelector: "operation=buildlog-parser"
