---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: thoth
    component: result-api
    service: result-api
  name: result-api
spec:
  replicas: 1
  selector:
    service: result-api
  template:
    metadata:
      labels:
        service: result-api
    spec:
      serviceAccountName: result-api
      containers:
        - name: result-api
          image: "result-api:latest"
          env:
            - name: THOTH_DEPLOYMENT_NAME
              valueFrom:
                configMapKeyRef:
                  key: storage-bucket-name
                  name: result-api
            - name: THOTH_PERSISTENT_VOLUME_PATH
              valueFrom:
                configMapKeyRef:
                  key: ceph-results-path
                  name: result-api
            - name: THOTH_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  key: ceph-host
                  name: result-api
            - name: THOTH_CEPH_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: ceph-bucket-name
                  name: result-api
            - name: THOTH_CEPH_BUCKET_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: ceph-bucket-prefix
                  name: result-api
            - name: RSYSLOG_HOST
              valueFrom:
                configMapKeyRef:
                  key: rsyslog-host
                  name: thoth
            - name: RSYSLOG_PORT
              valueFrom:
                configMapKeyRef:
                  key: rsyslog-port
                  name: thoth
            - name: KNOWLEDGE_GRAPH_HOST
              valueFrom:
                configMapKeyRef:
                  key: postgresql-host
                  name: thoth
            - name: KNOWLEDGE_GRAPH_PORT
              value: "5432"
            - name: KNOWLEDGE_GRAPH_SSL_DISABLED
              value: "1"
            - name: KNOWLEDGE_GRAPH_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
            - name: KNOWLEDGE_GRAPH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
            - name: KNOWLEDGE_GRAPH_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: thoth
                  key: sentry-dsn
            - name: THOTH_CEPH_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: result-api
                  key: ceph-key-id
            - name: THOTH_CEPH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: result-api
                  key: ceph-secret-key
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
            requests:
              cpu: 750m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
  test: false
