apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: thoth
  component: adviser
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - imagestreamtag.yaml
patches:
  - path: put-into-infra-namespace.yaml
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: adviser
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: dependency-monkey
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: provenance-checker
  - path: put-into-amun-inspection-namespace.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: dm
