apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: thoth
    component: document-sync
  name: document-sync-job
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/document-sync-job:v0.3.1
      importPolicy: {}
      referencePolicy:
        type: Local
