---
kind: ConfigMap
apiVersion: v1
metadata:
  name: amun
data:
  amun-api-url: "http://amun-api.thoth-test-core.svc/api/v1"
  amun-infra-namespace: thoth-test-core
  amun-inspection-namespace: thoth-test-core
  amun-namespace: thoth-test-core
