apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sync-template.yaml
  - syncJob-template.yaml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app: thoth
  component: solver
patchesJson6902:
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-

