apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aicoe-infra-prod
resources:
  - ../../base
configMapGenerator:
  - name: config
    files:
      - config.yaml
  - name: plugins
    files:
      - plugins.yaml
