apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: sesheta-srcops
  app.kubernetes.io/component: github-secrets
  app.kubernetes.io/managed-by: aicoe-thoth-devops
resources:
  - configmaps.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
