apiVersion: v1
data:
    github-access-token: ENC[AES256_GCM,data:5XyagrfE+eajfw/4w1vj2OKBc2IexRzfD9Oe5neDTsEuhtVljhUL/aF/6elyjPooPpYGEBMvIqM=,iv:p7bDMeIkHRSAvr29Umib/tOl1ISJayGZB8MjJNn4gxE=,tag:n/Gpk+PHnTfd/vYCkhoDRA==,type:str]
    github-password: ENC[AES256_GCM,data:7mjguDEi/pW+sT3Woquf0JD2Hb21O8RasD1fsUzbVRSifTPf3D2KTmCycJk=,iv:sN62K7uYA2AN4//oA9XACvsTXESvHMftr0POFvwzTw8=,tag:1/+1l/2RK+XSJHQJd16s6g==,type:str]
    ssh-privatekey: ENC[AES256_GCM,data:lpzPKXy4T7If+xO7AjWakImQQ/Yt5o+PLSikSyAl4Mj78w7TTyFxNNU1vgz8gE3D2S/E0sFzS0YghYhwgKftjYxgw4+MfK42aHLiZYb7UjPAnqsN6L9ACOHQ8uRuS1PbWM1BraW+wXpkn1yd0TesSZAFsbwDTKRW4q0MfHd1zL4af0ukJm/zlH3MepsKrbZXI2zwgMEbXdAYC92OCSe0yZq6J3KBJeJpN1Q30G0y0iryZ+fDrziF6l8o2v2FsdXB/sAvAVJZxlvmcnhAz7n4H66zlPTPIRyiiuKQoDDLNHAKpZMirVSgxVqW+bSe7CAFTF1g94aLvf6g4XCM5QpfIZ/lDMA+P95Z7wluzVvRDigvU1V4sZZHksJ1fpZMR5WU2KsYhdNJNQEsAHAIaUVizW+yYviGWaQhUa51R7rIN38m9PktzFW5ReMYJ+Igj3O7tHocNwrPUO38i1uxIa/p9WplJRV9reZELzH4cOdGLbKFpsmFcBkuAL0cXUI+2vTaahos4+JF6Hrq9edon5Dtkxq8CK+uf8tJv402GSD1doiorwWW6i/Ej9TEk9NGQGQ3EmTpM9INaJ5dvUj2zh50cXShoU3Gbla91WBQRaYfxNAkHEn8hXgW1iupr1+pXMAqVy1XqMF3DOjdVsc3GlTwGbj/0kzRHFSAg0QwADZKkIW6HvnQqLY/x6pT28wf60rWr2qaPkMHt0rZRLxd3D5zAn/ZC4yLPcSDNXwZlaaj1Dl04+Ujuj4puMEpRhgB2zHv,iv:2sRBro4QeuLnFJPz8Mg3w+vE8gf5Fta4gqi/5sjFInE=,tag:VxIA48+QMIDpvGsL4kE6aA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: thoth-srcops
type: kubernetes.io/ssh-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-10-28T14:56:45Z'
    mac: ENC[AES256_GCM,data:v7dIlJ86kbjumC2rNMPm8eZUxi2L6wY66PrOSa0qGB+FL5Vi9HXFjZ4ydRAmyTkgdd8yFeIUpbqNeDjAxqcB1tsMJrLD3ZlQVC0i2WDxeRCS3Oi3tFE2eC1Nytkm8pTm6/E7I0Na8Nx6Xz7IbcLX5mwJL2JxvLYC6hUDGQXB0lI=,iv:EilJLKUrGSG7b5B1gD5pERb/qK1u6il2Wh06yYzIF+Y=,tag:Mskhzzy2AqcuuPR3vQEudg==,type:str]
    pgp:
    -   created_at: '2021-10-28T14:56:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYAQ/+PqZurscoTR3K3mbZiSRwb/57+1AiuC/rGZmoPNpc+r42
            QPcuwK63/VQfFIT95GRzjEHYRWbGkpjB2S8xTOg/u4Ksi+NuDd7ofje/Kghjg27i
            rPHaCQbVaDJC0b6ilU4uyHm8s4dXNWWZSqk8GOgk/Ei8Hl+PKoKH8fcM9MEgyfQ/
            +KD7yTp2CBcxk36HEgDrCA8H7XNRdhWlUczbiPCrEvNPQHT2GIhGRqMcbtIN1rc0
            UcI3eFF2OZb7j0cdBkX0wXUQ9wYLvwYaD3Ex38zQMr16gQN1EcBp/Hx50tlbvUpY
            XJzyELAig1nAsYdQdNigux+UhFVFvkX7hRk8B8cJjfN7xLpB67gnePQTURJFAlBi
            lWL8UfY/ZSfu2iL4vg66M1xKtwaC5BB5ALJ1ejNB1aLJaoQzY+Fr4cvsb5n0Xi2+
            XkMzN5q1gnHTh3N3EHhP+fZgJlks2VNd4jAudzLkqTY5iq7e0grqOucgedE953Zf
            P3u0L6o20JhvwhU9/IGrDt6bG4u753WXwodv8A6Rep//nC1qk/x/FGWgaMpenzP3
            TcKGYQZeH6GqMhH0W+/6uOg1sv38Atc0K3U4Tvc+KdoRdkIFqApDj/vBSbo15VV6
            Bf/jifgdD8tPiP4CmUHP9QUZ2GYwoj1JOmodP/85dLBkauUUfdY8ETSKIsb2FYvS
            XAGUuXpKklfznbD1BD0xSp61LyLgqdZteznkHix2SOIDQlMQJ4bHEtFUql4ID4p/
            dMjfaYT6nmwfIsdSJiT4NrNGFd6CTo+koUZpPNud+2JsXp8qqPA7jIIRoBGM
            =tR/9
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-10-28T14:56:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf6A1jKVcfXaL8FjXNL/c9OEWf+EZOEqTuuqp9bxREvsoSl
            fpsYh8PjFhllIBXX4Xa5en1kGk/WhPbytaQKvpMyY3mO88NDzt3dNQmlgbHOjxBs
            c1TMNMhkNmpd/7A82Ej0IQmyzPCiQunktTsz4UXPw+tjNIXpf3ZczkznBHVpeu6u
            9TJTfw/JnfjovBdp1P/nq2NbZ4ODthLRGi5TlzTZfu2cfT7kV+BhAUqx54NqVLSk
            ahKXSvWSSgenl9FkwqMZZjwpCZNUMK0j8D0qircQkayJcrYtnz790x7Oe/Uy6y9I
            r5qvSXNCe8AP5u7hfR6eqVhTC+Os8371T4uOjD+Tg9JcARl38UalbjJTpm9zBYNF
            ko66zuw1CjFa9BGaTlfBWptyIMQ7rg/1jKj/q0jzQ25bZ7BCqUoy3NHh3tV5EgXO
            fADMMcEJwRB/EWDH3xkxDZw0YHYQgcfrSHYW1UU=
            =R/xV
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-10-28T14:56:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf9G8pd1j7/PX3cIAEM/ZUAg63OA3sIIlf+vceI8o8Ugq2z
            jzxqTERkkXKTyttH2CdANAF3zfdfIgSm0shm67egtSs84nZ+KiLjn0CxQ3lPZmdk
            +UpRX/dFpUqO6KQQJLQEsJ7DHWJGaVEPNFXnQReWjCdzRrbYTSGGFfR9XRPWSq6V
            /JI6bztxD9nxfigTZePfctXonsHAWnMswzn1zcAjf0ddcs5SnHlHsKwEz06gcRHy
            UWRz0RClVixPK54BgRIQj1rnNx3Trx8wX4LdAjFV87cvnJDvnNYWoETUCeCQ5U0A
            Yz3bCjY4jyR0tbfYkzRPL1Qx2WXzFKDZF9SvsvhqQdJcAaSbGE13x76uUpZx5krV
            MOXAzM5OdlX9JuRkz1DKpT5whVXkZHyA4fO9TT7yD+lfaS0wHPpuDAKutdhUzjZM
            NuyfnA+JjHPe7Rb4xiYnPalU/6v7huRiDxhqRAI=
            =Vhe4
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-10-28T14:56:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//b0ZwOLpEgzsjWfxVhaEtAzW+yCuBQR3152rmoM+rM186
            Gmxouvu7vok3v2HcIx7NSOlg7uMotTrP45bCkcgBr+ClMWK2jru4DOgumLSYQOPh
            OoKFFfv5yRoVI2squjxvOEcT72B3J78MllX/Zt+PpI6R185HSZG/fRQAxUB+2LSp
            2PPWDOIC9oW9FulFt80ytEIVpifB7GCQ/bLeRciR58gPMDTjb6BSNLR5xFstOTUp
            KTkmt4sB15DpgMlFmSOn13OQWuE4jPJws/JOopBeT/Fhs3rkX95fhTRh0GjP86Uj
            DXI2oxFZBM/bOjj5C6+INb3y55l8TmAOrCWJLdWntzoXXh9qoRLE6Aci2gEfUHoR
            ihrWu1jZzcUXuIaH3+yPb64IulHWGvd1HckH/WzLx9lLK5lkRFLBcqCRbjQjMHA8
            WMgvXV0Wh4963eyReEMmimfOpnxkrzoU3NxkHhgQzvRo/cMy6wmnuFY8jBEFn+Wz
            v2vs+h8VqRSSExv9ECPwJMqCpfMzp15CfdtHAt8qqHOpNb2KSFRANwq9KS2G5xlS
            77JkcNS/DE1zHIMHxI+B/0MHwiOo2BY53k0yvgMApLTkVOeYjxVUBUlRY1dbLfXu
            fELfK3msFUexQ2kbfztOEe9XM298SRal3hajTHagURy0IPaWrAK6IxvdHN5Dd0XS
            XAETPzojLBXPCU5C82gXdzwMo66rTnIKbWzWasii6f01JONxmPusw5JSPTS4Rnwd
            F5IEatKtFWnkM1d3GnhvE5bm/NjsPfDUOs2B7iyAD70EHy+Q452ncs8sVOVV
            =RA9W
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    -   created_at: '2021-10-28T14:56:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIOA9LRbhPydJmLEAf/TTqReBdqCuZfjyXF4Q89RWGvCW2QR01Ni1popIUce2ax
            XrLxser2qRm2xO7Bw+4x9maFbM4ZJtwzw1+l8Ij51ZT44hpwNnC8+xN+Jh7eDrMM
            LRToreiVOewzliDC2yWuykp4K8Gq9U6xX9lHaouUEfqrYeYpibN6Hxll+mTqrEq1
            eO4Ruo1vUGD8CnzeLMmUD4aFU0DteEG/Qvfc3xdx5JDUdyv+qkvmhT+z2Zh797kU
            1QG3JnKaXv0H7xBe/HSPQwq6Qv5Wb1vJI017jenund7OJOMKhI9bBVAWuIvChPmg
            4QjT4i8W7D0Ae2trgJQHqYZfg5J7LjGVkyvME9BUlAf8CWyzhQPR3PDw8awhKxmO
            UGAvpkb0v+9gso06v5sRM44FtEIeNeDqtUo5A+z01DGLwrbxLLifE5KnWPFPZOfV
            Wvwh/kWbNJhn5e9xhMH3woFLbLDpPI2PEIH37oZvDPxqC7fnXK/W778UpKe+uqrV
            odSUKLGZUQj7HVTcoA4Z90U2RQFtfZmOqiQkmyX9bjZC2Z4FbVcTewtbFkvBco+1
            StPdfEgyjkq2+FtWib932+lU50+aiPqln0C8t4SoDtXUc2Q6XDXST862EvtKnvhH
            ZfqlZs9dlHZDPqoheHx5ZLTKE+xcLTCV7aw4I81a63WHWk6oVFJG+Pei5CjMqtlw
            tdJcAbGmnhVWJLubDgQpIrdR76fsK4dWw8enIkgrOVvcQdD/u9R444Q0L6ukSoGG
            27ALp7ENK5uRM1g1iIm42w7beje3H2jeZR9hd0XQECnPezFxxB9XlJ/0rX7aWr4=
            =kgis
            -----END PGP MESSAGE-----
        fp: 8D191B7544E9CCC3547B25A877E5A5B31D13A647
    -   created_at: '2021-10-28T14:56:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9NBwWNwg7uAAQ//UbYrUxWZSCaOys6Kva4lrCm2bbzAwHbJ0u6FxF2IwHnZ
            RTQEvuWT0dbGzQRZpSnXga2mh2Txbh25CHDIDCf878dkTOpejv6LJd8Oyzbr4LgL
            ajObkPgOV4m6+NMeGZ1HgF7MeOI8N50wgvb1AZ3eyAGKOzNnW6ABglzL3HshtYcs
            6O9D9+UASddjeH3wcBHog3yac0Ia/bIOVKEf2oZaAJ+mmBI6Z17UqA+/a99endHp
            FbHSkxX+GjDlRboMr3ArsJEse2rRBKlIvZVvoU419E3c9zRkeIlQhhv3X3/3WOHi
            CT80XElhlZ1DMgzdI0HMI++VR1sWAgCpc9l9mzoCWSpVrrdQRaEZRBDixD46i/de
            sZ6Vnvvzug314uY/uQB5eNWoB6OWtPR4czFWOhbDW/tixQnasErMpcy6/yODjA1I
            il7LLI5gi00AKKmI0kEdjJjDWjiI/9vFZU2bRD5yImjsUl99MTFD1Idi862B2h9H
            H9+AeyyDlZC6CuVhQg8nuZmqwg18wKux4bFMnc3NQMr4smQySWIj7//asjSGTwDL
            MLuozhOokI6qtVehTDb5V0BbF1zVjqlaJvBjLv96OutsC9bBxsnYzF85j7nBiOn0
            e7PoET2miMrdTNrkYxuN21IZ4XKGSvWNpjnTtTJHPy6dq3XgPODEbDw379rRs/HS
            XAHLdP9H12SALnxyqWu++PZdPZJRlkGtKLFhPhQ9chr2eS3EDAyFy3LMiskriIzz
            BevNALwLfC/8oKg9OQtY5Fhe8CqOQeXFv7jP8x9xqjLcqENC6WrvhrDDTlCS
            =HfYM
            -----END PGP MESSAGE-----
        fp: A01778ACB7CC4D41B00FDD78CCBE624D8FF6D016
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
