apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: alerting-rules.yaml
    target:
      group: monitoring.coreos.com
      version: v1
      kind: PrometheusRule
      name: thoth-alerting-rules
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: --label=environment/aws/balrog
    target:
      group: apps
      kind: Deployment
      name: github-receiver
      version: v1
