apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: sync-job
resources:
  - ../common
patches:
  - patch: |-
      - op: replace
        path: spec/spec/workflowSpec/templates/0/steps/0/0/arguments/parameters/0/value
        value: "adviser"
    target:
      version: v1alpha1
      kind: CronWorkflow
      name: sync-job-cw
  - patch: |-
      - op: replace
        path: spec/spec/workflowSpec/templates/1/steps/0/0/arguments/parameters/0/value
        value: "package-extract"
    target:
      version: v1alpha1
      kind: CronWorkflow
      name: sync-job-cw
  - patch: |-
      - op: replace
        path: spec/spec/workflowSpec/templates/2/steps/0/0/arguments/parameters/0/value
        value: "provenance-checker"
    target:
      version: v1alpha1
      kind: CronWorkflow
      name: sync-job-cw
