---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: thoth
    component: init-job
  name: init-job
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: graph-sync-job
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: adviser
spec:
  lookupPolicy:
    local: true
