---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
data:
  plugins.yaml: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |
    prowjob_namespace: aicoe-infra-prod
    pod_namespace: test-pods
    periodics:
    - interval: 10m
      agent: kubernetes
      name: echo-test
      spec:
        containers:
        - image: alpine
          command: ["/bin/date"]
