---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hook
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/hook:v20200902-b5ff4681c3
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: plank
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/plank:v20200902-b5ff4681c3
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sinker
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/sinker:v20200902-b5ff4681c3
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: deck
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/deck:v20200902-b5ff4681c3
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: horologium
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/horologium:v20200902-b5ff4681c3
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tide
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/tide:v20200902-b5ff4681c3
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: statusreconciler
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/status-reconciler:v20200902-b5ff4681c3
      importPolicy: {}
      referencePolicy:
        type: Local
