---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hook
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/hook:v20210121-548289bef2
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: plank
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/plank:latest
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sinker
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/sinker:latest
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: deck
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/deck:v20210121-548289bef2
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: horologium
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/horologium:latest
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tide
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/tide:v20210121-548289bef2
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: status-reconciler
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/status-reconciler:v20210121-548289bef2
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: crier
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      name: latest
      from:
        kind: DockerImage
        name: gcr.io/k8s-prow/crier:v20210121-548289bef2
      importPolicy: {}
      referencePolicy:
        type: Local
