---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "deck-pods"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "deck-pods"
subjects:
- kind: ServiceAccount
  name: "deck"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "plank-pods"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "plank-pods"
subjects:
- kind: ServiceAccount
  name: "plank"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "sinker-pods"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "sinker-pods"
subjects:
- kind: ServiceAccount
  name: "sinker"
