---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "plank-pods"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "plank-pods"
subjects:
  - kind: ServiceAccount
    name: "plank"
