---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "sinker-pods"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "plank-pods"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - list
