---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "horologium"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "plank"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "sinker"
