apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: thoth
  component: adviser
resources:
  - adviser-template.yaml
  - advise-template.yaml
  - finished-webhook-template.yaml
  - imagestream.yaml
