apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: adviser
  app.kubernetes.io/managed-by: kustomize-ksops
resources:
  - argo-workflows/advise.yaml
  - argo-workflows/trigger-integration.yaml
  - argo-workflows/qeb-hwt-integration.yaml
  - openshift-templates/adviser.yaml
  - imagestream.yaml
