---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: metrics-exporter
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/thoth-station/metrics-exporter:v0.6.0-dev"
      importPolicy: {}
      referencePolicy:
        type: Source
