---
kind: ConfigMap
apiVersion: v1
metadata:
  name: thoth
data:
  applicationName: "thoth"
  fork-namespace: "srcsops"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: solvers
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka
data:
  kafka-client-id: "thoth-messaging"
  kafka-topic-retention-time: "8640"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: pulp-pypi
data:
  host: pulp.operate-first.cloud
