---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: thoth-toolbox
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: workflow-helpers
spec:
  lookupPolicy:
    local: true
