apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: thoth
    component: prescriptions-gh-release-notes
  name: prescriptions-gh-release-notes
spec:
  lookupPolicy:
    local: true
