apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-thoth-kebechet
spec:
  destination:
    namespace: thoth-test-core
    server: "https://api.ocp.prod.psi.redhat.com:6443"
  source:
    path: kebechet/overlays/test
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    targetRevision: master
  project: thoth
  syncPolicy:
    automated: null
