apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thoth-infra-stage
resources:
  - ../../base
  - thoth-notification.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
