apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common
  - argo-deployments.yaml
  - argo-imagestreams.yaml
  - argo-management.yaml
  - argo-ui-controller.yaml
  - argo-workflow-controller.yaml
  - configmaps.yaml
  - metrics-exporter-reader.yaml
  - thoth-notification.yaml
  - https://raw.githubusercontent.com/thoth-station/thoth-application/master/adviser/overlays/ocp4-stage/imagestreamtag.yaml
  - https://raw.githubusercontent.com/thoth-station/thoth-application/master/graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - patch: |-
      - op: add
        path: /spec/lookupPolicy
        value:
          local: true
    target:
      group: image.openshift.io
      version: v1
      kind: ImageStream
      name: adviser
  - patch: |-
      - op: add
        path: /spec/lookupPolicy
        value:
          local: true
    target:
      group: image.openshift.io
      version: v1
      kind: ImageStream
      name: graph-sync-job
# wf controller image patch
images:
  - name: argocli
    newName: image-registry.openshift-image-registry.svc:5000/thoth-amun-inspection-stage/argocli
    newTag: latest
  - name: workflow-controller
    newName: image-registry.openshift-image-registry.svc:5000/thoth-amun-inspection-stage/workflow-controller
    newTag: latest
