apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo-deployments.yaml
  - argo-imagestreams.yaml
  - argo-management.yaml
  - argo-ui-controller.yaml
  - argo-workflow-controller.yaml
  - configmaps.yaml
  - metrics-exporter-reader.yaml
  - thoth-notification.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
# wf controller image patch
images:
  - name: argocli
    newName: image-registry.openshift-image-registry.svc:5000/thoth-amun-inspection-stage/argocli
    newTag: latest
  - name: workflow-controller
    newName: image-registry.openshift-image-registry.svc:5000/thoth-amun-inspection-stage/workflow-controller
    newTag: latest
