apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: sefkhet-abwy-chatbot
    newName: image-registry.openshift-image-registry.svc:5000/thoth-bots-prod/sefkhet-abwy-chatbot
    newTag: latest
patchesStrategicMerge:
  - imagestreamtag.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
