apiVersion: v1
items:
-   apiVersion: v1
    data:
        sesheta-srcops-access-token: ENC[AES256_GCM,data:/pIyrlUIrEBPA/OQn7xGGRCQjT1xs7ff6RKEZN8tQ2+Kq0YjCNR0YpSNlw2DXVn5kPXitheCfrU=,iv:qJa9bNF/a+3Ph4Yda1R6ragB5xD2iEsBfgQH17JPxhs=,tag:kDp4lC4Ox37syWJp5wdzyg==,type:str]
        sentry-dsn: ENC[AES256_GCM,data:wlOr0w2sqYsxzrjQA6u7a4eV/r+l0Ne+caHFI0ZXZ9X0z+D8LBg1lybrMOIMXJoD6P/RFm1w913effNmoSqWIU7C9QE1FGxTNz7MtomLtGs=,iv:2a6GiBa6dRlqvT6I0YwLoAZPT84kE95uFoeWQIodNls=,tag:I3Guqj2JQijt3DX5NMxEZg==,type:str]
    kind: Secret
    metadata:
        name: sefkhet-abwy-chatbot
    type: Opaque
kind: List
metadata:
    resourceVersion: ""
    selfLink: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-03-16T20:37:39Z'
    mac: ENC[AES256_GCM,data:uDj598XxLrk+5a8URJbLEgXQTWepraZZzVIhVni+A9cHJlEMDHT2zi4tDHyzLxp/2wAl6OkRR/xFSFtMxoljEw4oDKshkA8im0nxmvsVS3QKmK2tP4E4qIy7KKc2yB1biyBS4XPAV/JoODyLyYgvB0jzzVp4fiyM+L0tlAPSTbs=,iv:VUK2O3qV4UIggvP4SqWgzZRN5YHPv40iTs/74jDGlKI=,tag:WgJ/ibL7CpnduEhzHhoxqg==,type:str]
    pgp:
    -   created_at: '2021-03-16T20:37:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYAQ//UFK5KJXvCBwI27SuiCekSAT/gcaLhD7ZzTU+dc82kVB4
            wkbc5Lnq6l6o6+IHd9HsQYg2aeW94oN5Rfw4wdCxWFY4mtp3osS8YSE6v9gjpyLh
            GL22WY8wwOSZSi56jTmaED76X4sPJpht2n+7AuKqYz661R+TXZ87Wm2gB4Xfd1fe
            4mSGsJh85D9DmWJjoTKm2SZuQuSwK+Hhn7vkc6x4wXlnhQOwz6S7XsJ4wg3l7IJI
            kLlik2B36/7SktlH5VPgPLBO4CK+ET6cfhiDvmR8yBi0ADlK4A5XiQrBNKKZtuT3
            8XkeRHAlATyJQMwI88sU4dMGF1M3pqIRGiYZMZk1EHc9jneB2je2K33oaQ6mysBp
            2hEdVpwMv7ymP1QRk6nDLnhzKkFt38iOzFzpu1/LRVqQqVJ6zQFqphuxWe7PkuQr
            EkzJD38zBg6m8fEktHQjHlHkAAOSiQGT6ySxBNvQdXs3deyVFg0xreYM4oed4NwH
            EYgZlRTV41O1v4RjkTz9q7YSPAUOOBQG8oGBBi2wQzCJWyDlCaMpFaDCsKP+9TQv
            0Uda9UJ18zAL/NWmzH+zUmKksBGRt8B7tSKmRZDV6X8BdBQlooCFXx65aQr2aQyj
            jpigwjhmRfllHfaEoZ2uP4KfvJzO/VOHDxoJGxQczgb0CmxNPay+JA2tjxOD9LrS
            XgF42/4W6C+30iiCdsvEEsefdfUmoR5HkmM/yHguchj5kbnFQseNnESzrRNN4uXZ
            IJPKUz5occBXiystSBxPmiW6CgIT58LYJyeEMGY5MF+rsbDTri9+yukif89hzIk=
            =N/o+
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-03-16T20:37:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf6A9b4Vp/dih52uPd6YNfvH/Ch48UCbEW21DGDwE0A2JUg
            N5mlhYk5jbjDAir+Cftpggspt+V/WM48ZtSBRPZSVxTmVgkym/gkZCmDOkqNzGD8
            SilY/qR496WclLGhX6cI9P+ICOCyj29X0pnm1BAWCdncHgZRPlKLiRWlmD1A/Mef
            r60jdfZDSX+TM3l9KmRhD95Tqsx8d42WWm8Njc57Q8+w+b2lr8nICIQ0v0SddxCJ
            q9XXfMzI//V9KXV6X9mktdcC/iqGJ+yfjRoI6eWvEPtNLMI8e2GG3K1Z0Qmu7ZYA
            UZvonJR5CtiXJhMKZrMqlr6RGmXW2sBJadGfYnmCcdJeAT4CyGHVYqnaNo6ah7oK
            TjZotV0X8vYYjS6jhfiCgbMsvP4njGqR9I/WVi7KDUN4/UhB71EFua5h6XeQekrV
            Ge5Zuu0NAOzQzksTK21+jMenNOMKR0ZcGviRzoXIWw==
            =YKiE
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-03-16T20:37:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgApJpcdbX6AC47qkaF+fnP2MYRHiJXyHjF9jDPLYsp+t9L
            ZOJIXSZvJMae66Jiz1IPSPdjYT3LEZ3TQY1+/hiZ/HOO+SU/mUs/1tPlGUFpogPa
            odvHxTTUIyzjbsz4yakb6+Tg/r+j1Q7N/rfjfSpH1SxOmlP2d1ixok519bUOivnY
            GcrCod190TWH2a1t+ua1U8MNMIvzGH8qta4eGcsTn9tZ22uYbHsSGuDnJme/8fo5
            XkDzaiT9xYC9r+7Qrc0RfCrFV2jkgz9J42CpeVdIKosgNfVmgogwSNf4UCV6WK/E
            kiFkuYzbERb/yjuzCroPfvlWs3uAMPjN2tKHgr74PNJeAYsFMw978XWLogoTCHAl
            /8LoGK3hxnjl+zMPidpa4B1R5v/Z+/tct3408TSTBDljDKIPpuoa205C2/8VSFc8
            sPjGZpgZsVlY2+2fTu4nqgL8T/WwOhkX+aH/OYnmYQ==
            =FtrO
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-03-16T20:37:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//Qcl5lqfjOLD9Oq21HHy9rH/4PPsm6RpEtlmnRRXX1/t/
            IF7jOf9qnrLfQyFHVJpHnj2m9qRNidDgTakvIc3+BBiJFXWcmHjwCdY9EpHDw8Zo
            z7ldpVegJ/aJC+HNHnDnT+gmb89MVZl5U4STKoY0tvm4ERMsQHUQ92T2hw6//Z3l
            3+APL3ES0sFO67Kq6qJGRG5t6QNAegfwoK4cVwLFzyEBLelLjLTkClPiOUgXw9j3
            bl50eMYsDxmKPosUgF6aqFAkacahs8R09Rkdk8u8aSSlICV3xYtMWjNtxfeOvLwm
            g+dd5SPaBHwrsCozW3+PbLPmaaYBide0RZ7mfpdhqBRSEh/3ismKmGGvMsc6iuMo
            Ay5aoMbQ5X4/QowpTPP6snIJNg7JnbCx0Edq28asKCiRLUB26OZ75lGTzZAxUJXc
            CoZqv+iGZwZFKBMPkdGx0jCHH+eZCCGhTlVYq1Qn2wwa/vrKyIofaQBtChR7IP+P
            TVyFDjid/BP+3hJvjRM2cNsV9NL1kQN4mJrqoxgc+vjXUu89c9lKdc/Q1U1k7M69
            gicJI5ZeH8iZndp0OS6OiXBtpm05B0To9KvBgFpmx54X1rYHY46J/Avh7k07V6ET
            g4IWkEdFXSIy2QXinGNQ1N54l5qchYJ8mRXRN3oI9CfoJwiOkxxEmLl9HPucnJHS
            XgHBXIpHWoyH3v0CpjggiX8qvh2hmFzgGA0n20j9iAkgM5icx+9kPbfL7bipIAjb
            /zL4VZnGIegMReU5dYlS2VD9PHDoS3NU1BhmRteHV6UraMKtHQ/gIbHMAAZckv8=
            =0tcD
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
