---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: trigger-integration
  annotations:
    operation: workflow-helpers
spec:
  templates:
    - name: trigger-integration
      resubmitPendingPods: true
      inputs:
        parameters:
          - name: "WORKFLOW_NAME"
          - name: "THOTH_ADVISER_METADATA"
      outputs:
        parameters:
          - name: metadata_origin
            valueFrom:
              path: /mnt/workdir/metadata_origin
          - name: source_type
            valueFrom:
              path: /mnt/workdir/source_type
          - name: git_service
            valueFrom:
              path: /mnt/workdir/git_service
      container:
        name: trigger-integration
        image: workflow-helpers:latest
        env:
          - name: THOTH_WORKFLOW_TASK
            value: "trigger_integration"
          - name: THOTH_ADVISER_METADATA
            value: "{{inputs.parameters.THOTH_ADVISER_METADATA}}"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workdir
