apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: thoth
    component: prescriptions-gh-release-notes
  name: prescriptions-gh-release-notes
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/prescriptions-gh-release-notes-job:v0.0.3
      importPolicy: {}
      referencePolicy:
        type: Local
