apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/version: "0.1"
resources:
  - ../../base
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
