apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - thoth-notification.yaml
images:
  - name: package-update-job
    newName: image-registry.openshift-image-registry.svc:5000/thoth-frontend-prod/package-update-job
    newTag: latest
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
