apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common/
  - service-monitor.yaml
  - thoth-notification.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
