apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: result-api
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/result-api:0.7.5
      importPolicy: {}
      referencePolicy:
        type: Local
