apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - thoth-notification.yaml
  - role-binding.yaml
patchesStrategicMerge:
  - configmap.yaml
  - imagestreamtag.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - path: put-into-inspection-namespace.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: build-watcher
  - path: put-into-inspection-namespace.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1beta1
      kind: RoleBinding
      name: build-watcher
