---
apiVersion: batch/v1
kind: Job
metadata:
  name: build-watcher-chat-notification-success-
  annotations:
    operation: chat-notification
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
        - name: chat-notification
          image: registry.access.redhat.com/ubi8/ubi
          command:
            - "curl"
            - "-X"
            - "POST"
            - "-H"
            - "Content-Type: application/json; charset=UTF-8"
            - "-d"
            - "{'text':'Successfully synchronized *build-watcher* to *Amun* namespace, see <https://argocd-server-aicoe-argocd.apps.ocp4.prod.psi.redhat.com/applications/amun-stage-thoth-build-watcher|ArgoCD UI> 🚚'}"
            - "$(THOTH_DEVOPS_WEBHOOK_URL)"
          env:
            - name: THOTH_DEVOPS_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: chat-notification
                  key: thoth-devops
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: build-watcher-chat-notification-fail-
  annotations:
    operation: chat-notification
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
        - name: chat-notification
          image: registry.access.redhat.com/ubi8/ubi
          command:
            - "curl"
            - "-X"
            - "POST"
            - "-H"
            - "Content-Type: application/json; charset=UTF-8"
            - "-d"
            - "{'text':'🔥 *FAILED* to sync *build-watcher* to *Amun*, see <https://argocd-server-aicoe-argocd.apps.ocp4.prod.psi.redhat.com/applications/amun-stage-thoth-build-watcher|ArgoCD UI>'}"
            - "$(THOTH_DEVOPS_WEBHOOK_URL)"
          env:
            - name: THOTH_DEVOPS_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: chat-notification
                  key: thoth-devops
      restartPolicy: Never
  backoffLimit: 2
