apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: aicoe-prow
  app.kubernetes.io/component: prow
  app.kubernetes.io/managed-by: aicoe-thoth-devops-manual
secretGenerator:
  - name: prow-certs
    files:
      - tls.crt
      - tls.key
    type: "kubernetes.io/tls"
generatorOptions:
  disableNameSuffixHash: true
