apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: prescriptions-refresh-job
  app.kubernetes.io/managed-by: aicoe-thoth-devops
resources:
  - argo-workflows/prescriptions-refresh-gh.yaml
  - argo-workflows/prescriptions-refresh-image-analysis.yaml
  - argo-workflows/prescriptions-refresh-pg.yaml
  - argo-workflows/prescriptions-refresh-pypi.yaml
  - argo-workflows/prescriptions-refresh-quay.yaml
  - argo-workflows/prescriptions-refresh-scorecards.yaml
  - imagestream.yaml
  - configmap.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
