apiVersion: v1
data:
    quay-token: ENC[AES256_GCM,data:o2R1trDl+Mo/bz11yUPJnnjuie0utZfN8gKQ8gKETXe3xD23k19VQRu0n44zjVm4DI8MgTMoO9E=,iv:IYjXTVoQAY+dYQ+vG1TT8SFkxJesrWq7BxZoIK218ss=,tag:aXVk3qKLslI0xynRHUNN2Q==,type:str]
    aicoe-thoth-ops-b9fa132d5b9a.json: ENC[AES256_GCM,data:Oz59tF2mKMMuiHl8m/2Au9RojgPy2czktF8Xb2hZuOs0vsG8M/yxHZES2VBIoYwra3N+Maa4BsSGQYWsKMPjCiONreHbv4KUtIFhxceJE1T/6IXJ0SpdTGv1yAOkklPIEVrc7isVGyl58p8de5Ekx5Rm2K8rGRnWL2K+DumIymo4tNz6guHP9/fyAM2wU1eSJVCtOrmLtyGTC4v9xrcMkgAOaLizcbiUIDzFXpkL+NcngatvYFYh9EPuqQRcG8yrHGGJnWtsT+mbVNKTQsaB+18jnAgqiPzWuSQjeZzUsFLg4iBs5Y8+MW7TDXLd4TjhK97OTER2EKgXwq/lbYeIZ3M1xO1RTLOvgcU9AusHFqQOIUKFi48Cbrw7+xgRlRQO2LMDp3JELpRgxows465oSFZRMg3nYCJYwfnE2Id67e8l+72YJAoxVGcYhiDlSYUz2qUgDymJ5c4DdgR3f4S1dF0kjMPaBpEAzyv031VDwW9J6MhATzGLXJpPbLtQhIwWHJBNBLzTb39jW6RwsqcXKYWhyeZlPctWImRg9fXo5NfDsKzcaJcFuId6up4fkM6ebVfxXJqf6mESF6tLum0ggHgnrKQ220NBLfmcDh48r5yqNT5ctHFvDDXTKIUH3weNE4Ff/j3F/3c4EpsVzNsfm3tawAYYk9rfJTpGCAw2qOgOSo+6dGkAORq2T3wWjqN3GYSD4uYe4KQhvOVhXN6RI/T3CiH+NvnBT6IVmlaSGnnyqHKUUEehftCaUmlwhTto7I7NAwVnT6Jj5gRteIF6/FJaxjF4sKVhP86vUyfsvPH7HIxg8WCJt+H1a8ohoXsVAEMeZBrRV1pMlXFYO1e90Nrtkk82wWSN51fWUQp+EtoGe5ae6nGJ0lM6ELim+w47Y16i81rm7bLbA0KCfFB96ZP3rxokBFb3vuynswN/yDZuOhR+WblwLmUZwT38+Ii07C3MfdDGGvlxKY1KW1KP59BvSBYVttq7MNcU4DBCDKgpHIh2C+KSTjAwYdKK6rYR3XlfkTlVwwL1dutX8A+ZAb+apOTSBwxEI1H0d3wS8L2jTxQ+6Gd6JOKPPHN4favKASjELEZ2PAc5cVktychOQIKaC6tE1KnCAu7hUHMNTKZxlGB4VnC1lg0/q4DYwtJbpA40m3SmnsryLSxN2hIbf5tBgmpamCYzHyrOOAvwAZQlJtQ30D0kJpXmNVo1SRAOl38tfyr99RYdHIpAumBaDH7lTXYTdG4u2bkETFpBHi3fV0LL6CYl0gc39QeRh5GpR3xMzHaz4xm97zcFsFllmzXeL2FRvd6PpovAi8/k8i5rfy29DWp47mHUj+YPvpz7MBfJ0S6Bmx4rJJNJme1gor4S17WeELsCEn9IkGKoUlUoqnssfIgOgV7iss5xXQLLKJkI3Gsf73cw+oLg+PJ27bZ4ulbSvHnreiUnpYC1D7LmVqc34c5Ma06Q8wwSGCxgIKhiK6q9Lt+Kcm15Df35d46/uyU22iAJ2UhZzDpZQcYHZfX1QeN45kjuK2oN5VZo9JGdCKgj3DRMa0SVADM0+X3ECMigQR92TPgD9r7Z3z70oED+4XbC0g2dQqrsvOgztKNchZE6+YG65wi90NVZtqyT6Pgdqb6NBBo/x91QMpsdNqIUJYVUhi69SEpxMMC7UngLfQmsGRpPpCHx9lNz40YrCwmnXRBmpWFSNcOjKxyG1/rULUezu6RnkDR97uOpBnnyGICYlOvld1aUq5lEnZzCW7vfn/MWzdeYMg3VGULLSiYgWBLfC7WmUN8yYZPiOshywjg7EcBW7Kvld6xVLPo+PdLXbrjp37KIzK25WacOEHtoDeW8gwwAunsTAl/JLuk2C2Rm7WfdrDrlB2pAmX58TLkRKb8nBKdMYBdG33p2HVyiJLP6USAiKSE98/LM+h5WcZgVTjswGj+nZZHvGYPXoBBTnwioYjskHhcnZU5smOpCyVeddQQcLfY75oIOglO/xtRCzKz5IG8+iYJPwBMDiRoU/VW0wry+QjfF2hSglSrB2o/V9IbI3oWnXS7OOunA/AwMyO+pT2sxmszuwgTJqUlKPkoGnnGuBGE8JduG6r0uwTX06D+dESGax/CEZagvkjWV7cNk2OH8KrxIdCSGsylDwGZnrnC5vwGy9KIO48TmZtsFtunXUwvPuWpa3S3BAoFZtI0qDbvC4hMIFCPB5mCTFFlUgg/tJahqYcpXhPFRiDvqjGwT6bag85BBSQssmMNdfKStIu4hCylW6LVvsFYsWSoOYgXI5cIn4nATIem7WNlz3JGzgTX7/NiIx+hHhH31HpZ7+dUcTMrN2hVel+v9HKrFiU+bX8ckyPheyScNaNaHFfN23dl4nbElADjN9mRdJlQkdjUIUXihkk41am/G3vFPjQ4/TQ4OJX4WOqpipUppQED14eehPDpCLK+mkkbybfNULwzCvAqrB7uQFpsQODdN4KRKhbjOObVxCaPx1/AXKzzLiGjcEcZY7dNAMZfWazHODrL8PShN/NjcnySaL5EAQI/xgWZmxhMrVylNSe14JNCT93uonmbmLMELjr5qXhj9fyw+fwdc//zoY8Ao6vBmBREyWNpAMRAXqVFSgKtPzlVi/+b573ai3Iiu0NFsmqcMSqFmYkxb9e+527kb+kYNBNROb/0+16RKGVjRIvG+/B+q+EsWQzeccOIr19A7CE5FCprkora56xStlzUjK/4VJN0YD3lfyUSnMyZhwfP7oJiZ2pLcDTmYzo2+vuN7E+JWovnqw8Pbr4QTDPeGRcKPUyE+Xy8OmJlOW0KeH+cDIL6plzh95d+ftEYWz3I/lCfGlX1pvRyG5sCGpIet/+A6fbrc4lf8qXZKcCktvrMzno5q1r/It3MBFeRMAj11v8Rd7j+5BHXtl+aDNCC9KRHtMkeSR0KyyqWxiZV20XYinZEAaugQ4EZFAVAj2gFaz8D2stbgWBEE2wafFg4HErBChDok0nCl8GrPNx4JB1i1JzvJqq1lZRNZxkB5dsS0SuohUyEmvGFVfUjofX4500tLDGHoCLDMGmOQGSZvh7Cj+4QmQuIzIu1j6Fz6sL35LDnoJOXCEx5/flehTx4MvfbCtsYArELsG1hiWhW2ZzsyEOx+TkYxYuVtT3Z2CKhhVyDC5akv0r3+bibED0XlD3q6TSwTYdlQ5lt6ZnHDHnrdrg3IKlW4uf5WliXzP035Up1pifzey7JUFIOFDcqSmAWpm66Kyn0R9TgRS3OeMwQRquVFaPrCEfit0LNbNOPx9jAXaZSWWZ9y4sA4gQQIl3GA4KQhYR0PJmnSu1N2eXxL4pHVFqh299okjcB/ps0Zwu698LKdOjLxpguANHb7C9d8wS9MJpCz5ZXLjpkAFEEOzJKEbnBJ6NRpXj0WVE9pMH49s7sSM5EIDgw1KaATR0Fo8NF9ZAG+jF3fELlKAIW1HT2sSwiYnu/tu6a6FGsGcN5gY7JFk9SPW3swQLCEKxoYxgCGKRmpo43PwFtPXY0STb2tUMTGc0HvFJxUzL3SuVDop4hb0zjFzGpudVYFdUSE5yttotl8hoHfIgjY1k+hEPl2uLNdtC7PIlITVhnaxLUnzTGYQvM1h+p/dBPvNf2J7s6qwaRcCZ7+mJPERxoS5FLFC1053260QcVHLdfufI3O5x7klfy102OJmR9wE+HlycmIRSItUNp/K1BssgacS3+9tmkwR6ALUWYn/Y6t5mhhPkiGIIEwS5OUwAvJonZdK1UecXQJ7j+52Ws36+4K/Dhm9kuLHwbUc7tIpt/uZhoTEKDA3M73kLYNsgR8BLLkIZVOMIlV6WHJDZ648fb5miyw9fBSA12hgHgVOM+96bxP1LtwQNATIJzdkKjlqjsvWQ5lIMFWWyB225T7bRlfa4XCV23l8wqNyTrUasKAEI6TFtHwRKD7pirSD8r8BPSjPm5Ee0sfHOxllrPAEkmlXXeJ/0fuSiiMpq8AZCTaHhFOc7de8NIK20R0QPce1KeeH098ICcqLI8KZPU86Yn/49PMV4r3H5I03V5bcf4TI5AEpjLc1YLzEGb8nQXj8waUQpOq2ZYtQFZwdvaatxUr9C+w6xg9WXJrb5b3VuENeCRm+rERaegPHU3Q93ppRwYe10HV8ViPMfq5frzXzpKezbi3A5LcnFvyR5QTP7kqb5baW0y0BgsqIQ==,iv:2RSwL8cVArpIo3Fal4LBRuGcUiTGWlKOBLBePx/x+Nk=,tag:zFsdFWQqZo9vS8zivmnOGQ==,type:str]
kind: Secret
metadata:
    name: prescriptions
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-04-07T11:55:27Z'
    mac: ENC[AES256_GCM,data:Bv/1Cd3xP83qAc2T8uRuItdlgjO2a8aMFlnWwHHDqOUH+0f4PqJqB9/nnN+2bU9XR0Fqx16Nv6ErQROdKDTGUy0kuTYFSpPkT0PxM1HOzTR6dvM4MkJ2OYffg6tyosG0+ofVm0tRw5slFhHRRXe7r+erN1T7ATZyMr1bJ+XFTQQ=,iv:Dc6Ekf4LiJo+snAADylTMoC0bRDtDZyICR3ehOJgiLU=,tag:Gw468+UAauQx/5lx/r3wMw==,type:str]
    pgp:
    -   created_at: '2022-04-07T11:55:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYARAAnTHELu2K1gYoNTdvHaUHyFaTPldKTqdRkIgL5emrrHiQ
            vPekGDKmHtQ1bURlOgcvALYcUCQSu/1DnkxqO2wnQ/VCEM6/VkNFrA+WWkwWb1/0
            plZzruj1rMCHLoz9q92peG68cMK3AbYbPV4ou52SwjDAKXy1jwKMl5YMVf4F5coy
            JPmcYn9+MGUkxXIKc+dj0SXWfTSQk7SfCVJqlGm2g2z7CGGnJvBRjNRDy36ouwKl
            RQ+k3D58R9YE2SKX7HJcAZii1HmgPMlVa3Ux4xaOe/OWMpG6c3h1RxC6P+CTgv1M
            ScF67rvLe+WR4+yBB1+uwTRcgd8L/2CQJ4iYtOCvHUcMnHBkYStE0jG4fAySQlVP
            Fn0tqtvBDPcussvYXWro0TmslJ5hRwySVwy1/nkdoV5Jkyuq/Hh0Hwfaq6VRvkQV
            yK8nz/cDplfkz+7R2w421e5A8DMFHtfbLK2BhFdYthxTsBfjVMb7NRGdmfJdleZG
            0vefE0srRtGPKmh3eMMc4nZaErkFblTPiyhKQR2A9ShTVQ8ou54acztysD0Wadtw
            vfRDR6JTsneX+LfsM9TeztAxsRKVNvweIHpjb4cUeXDyphIu3lL0aXjGAaB431T4
            Cw0oUJVmpnJAQDrTpTLDItpvbDQPXJJbK5jURqC+px9Q0fN35qWNabfW5+OLCSbS
            XAGElb+qey9bBPjZo+f05Fqgu9MP7pJHwgRf8Jiss4kCtImTJHV4CstGeMk25yMj
            Z89grM78YqARivCk4OksGus1NfcyGKgksNCFMh0M5+JOsEptVdePKV2kadWL
            =3qe+
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2022-04-07T11:55:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf/YzInQXjScSxKGu2O5eRVAcKXuCUAriEMUSiVVM0sMm5H
            DDOzaJN0ZH/AOTrdjCyhGGlfIj6vDGqJf5S7LFKcW7+yqHVUMZg1gGdL8RMSgMCI
            XZiMmF/ilPwI8txjE5LYUrJSmhpVHh6bd7jZ3sekJl4WdjTp2+RkO/7Df56DXYoY
            a6xqVu7v2/LArtamT3Km8NdQpoXHoTY+md6pZOuB9NOFzXO4aoEVdFITbme3LI5+
            G0jIYvr1aDVjWWhtC+W0PbAI4ZObAHva8aVOT0wKdvgL8vr/pdroIjDB+FVgB0CI
            Vik8CqQWMBQoW22if4QUkZv/ZFI5GsZs0WT5Nv6oetJcAd0sFAjW7Jk3P1/xeGHI
            ODfqvWAUFSXapupYk6LAjpvK7lYy88NTGUXTn4Ex6+wj1KFoH+llOs5URIbwzzgp
            41bXIGxSFcCiE7yZMLsKxsq4n7rJFZUIIgGyNNY=
            =lvWe
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2022-04-07T11:55:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+LZbUGpG4BHXGqMsHKD86m1Ka2xAa4gqDH/ueV1+mo75V
            gWdAQHyerwD+TBk6pdiDA+Gkn3O0Np1YxY35tKc6eVbIPtWWMCRtyTGN2xWVL7Wu
            wq6jenkQkabKdEVzmpGdgTMEkxcno/YbdrO4HRIDzIKBnaoiIu0sXRHK7a6T3DZN
            gUiAgiaHWfMHCLWcZu6dW92Im887+GvsoEOm6L63NR9VQTG5WJvT9nZ5oDMW11GQ
            VrlfZihaWeMCib8sEYbyl2JlIwPjQul+oS4lmy8p5OZeCxuEJsL7HwoFQbXpQec8
            57eN/VoCwuH/OBYdtcBK+AcLuIy6gC3KmyKvcX0/FdJcAb7aB/3pq0CWmhgzweTp
            kO7f4V3FocRik91XbhYTFQN7mxgDFSGaPohslbV6dG5Pi5xRX4eHyJW4EKWLpPVD
            2XUe5fyckzBDkWplRmVHmIyluHhm91ucvCuBURQ=
            =qDMG
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2022-04-07T11:55:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//dfsaewvXlFvQ2HXc37hTqzC34ATdeZ0Yli2Mx0pVwQa4
            fAbyykW4VWI3iRIEvi1RD+ES2U4TjC9FTtoozpqtOMd/QsrwcoKkRgIIaLat2SHT
            9vmxx9upqFElIIg3IlWVP677hPNsY03lx9CrZy/vOH4Q4Mhzh8JJ9Gi3blFXzoig
            ysKt8ZHzuaq9iSdqfLTGeZIVu+g0P6wkjx2JZtiZZlh/TSzsqlVW32P34fwMYNJ0
            p7gD4IujWUamPdl3NONpbgojWxztNA1xvqpAVp3fjeISYeYn9CBemjPKg796INZW
            DkNm5nXrQ4CTBvHUaLzAxR8KTRYSAiyrgUciP9nqMTVY6MjrWWN6hCXXimtjy2Of
            E4eoiYbCa73qjqHbp3NkZeZ7rgkkfPmblz7QWc3NfUB+HF7JdojUvPlp1wzTLWv9
            JFksGKeBkAicQ+dEzb8/rv/RDW8TgzE9qSRdUljhPBUZ4mGBI5Sog8LgjXCoEzNE
            Rgby0dS5DgvDJNECG95PjQfgwmr04ugR8j6HZhHa6V5FAHPoaVBFwczmGVPlNEip
            /ej0ii4VCUP0QZe2pUkmVKc0s1v/FVw0/n87aftw9vNzOZHRhQ7plQ3zMQh6LZjT
            2jzWcLdni9nv96VP7zQblSLqY0LN55KWlxHD/tiZifE5j5aKuHr+QKc8vcFS02rS
            XAHs+jOHw2T9SjVHVi+Rx8C0uimVdL8e93/iTYSDw+FFPlGhwFRSJMkf1eiWt6NF
            /ea5v7GZu8elOX4j+aQ0LWc14sEkJXmEYfeGMg/GX4/o8yDmXwFp4uKNb376
            =9pWE
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    -   created_at: '2022-04-07T11:55:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIOA9LRbhPydJmLEAf/SH1FUM8lPWh0VPhgZNE05q6toaHpr0e7diuSqk/E0znx
            521Ga64d1i1/7390oTV6ZfVFIc9UKGDVgdffp9qUZ+PHFa9k9AUtNDUWSrhNo0f/
            kl5Azs5vokISY8lNZOusGJ0DtvKsFOItKYx3UPfeyVZCZ2nA7vPcg3YDwkjP1Aa9
            Xs140GNNYiXBUILA9+LyPHRUHhxOlHWAoSWx8HFJdg3B1s/7Qxlp5nQbzh77+uWi
            kmzVDCtRg7EcOJojbwKn07pheiAPYdvpG8ITx9s8ADVZeOXihEx84jNK9ljJUb3m
            E0uDu1c7j/60GjrwvKgcHCm6ffo6Gka9atfUmJBQZwf/e5GOzl1jdx+X6OzUN5++
            Vza0KLLbrsQTyOafcZ7XW1OXNMWUDDNI9FyihK47V4d3xIT0nkIj0+EIuhsLKy3G
            s5Zy29IVwXrQbQAvpqNwI8j8PkiS7P72X2f1Ck+1Eq841CeTsMM+hHTohVlx3tJ2
            qIf7UnYiPRaKTGFF04OBDyOlGLJ4sXfv9IhyFp+Nnya8+3vxVgcjMpn9owsOoNu5
            DohUdYBb6A7C7yfGQHHFEylpu8eHhw+WCIZmBWgxdRpeYNIf5B0C2PovGhdogwhJ
            C9zbbkD24vV64y0PE/khamZiGIkXYK3gTK0HxHDhG0dSIxNYac3SvBvzZuz3+cLR
            J9JcASivksz7O4pIUXp/5NPMY4aoWO0m2+KQJetmrOa1lCaZ07JD97T3bLD1rpm2
            6ceesowcmLM1hEZ9MvyYUODb3t34fEVk2Ay2/s6iEEnhYJmbAR+36IaQ+329GHQ=
            =dplI
            -----END PGP MESSAGE-----
        fp: 8D191B7544E9CCC3547B25A877E5A5B31D13A647
    -   created_at: '2022-04-07T11:55:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9NBwWNwg7uAAQ/+PE+IJrPzSU4Cb2Fl1wKlOtOjCT/vroTvFA7y0XKaR7jp
            E2MSYXImcRnFnFwsQnVvQTaegiNaDjMdIAxqlkN0qh2IDbEwf02BUBaUgQRip/1e
            PBfUC39CX4fKDYja8S4gAZGTTMfY0QPlXnwBrr+FUQpuxNz1ITYtpzB8jXjuZKLf
            Bvtaouu6kcAvUNh8Ahoa6xGZXFh/lZ0OdhuWtF2BcW0m77enWQQC57vfD1AOrCuY
            3EEd8IdubzFeJYedN8hyJXvuf3l7b5qEuEyzBlkq3gtkNq3Wjd8tpEb1IgGujXdM
            YRIqlASO0FZZIX/mDhy6hN+jYYFZDnay0QIpTGY6aBvQjg7UJ/erebvizK3H3beu
            p3hfh1XDjV8FAnSxeBW6IwZZtKDWC5mRBSTL+fRFO0+b6wQBh07f8TiDed64pu2m
            qsTpWtrzz1b73mwo1baIx1QyMf38v8tsL/wzGhm8Qnsci0AfPmH/PjtWZUIJyC79
            t2wcjQv7upELbVtpbJ8D03wifch7qtgB/mGAsSBfqZj1y/qKkUqkHa2F3x8F/9/V
            t+uLgEVx020XwZVODvSHi4M+GcWSDPAhSuTxfHqTDB7YJlbzH/g4XSbNdAB5LVLa
            ryAhaDFAqJ72ls/6obKlvMeJDj22gMQRy8IKHr+7xty6BIkrLhwRuRDAseeDHXDS
            XAGwXxSRm3/DwSWWyGdyOD0rkfMnkle7NzwSA/GxZe2uclk3qGQbFSdMO7iBZn7t
            aFQ852FgjRcdwWkFnorYdXqq4fgj+53X3qKkP+3FBxdDTAvZCCJkPdBBq6L2
            =z4yM
            -----END PGP MESSAGE-----
        fp: A01778ACB7CC4D41B00FDD78CCBE624D8FF6D016
    -   created_at: '2022-04-07T11:55:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxdcElc1DYwyARAAsc8pk8vIBjbMVDv7257ddCZNb+9CJF1WJW1ALO3Ko1gR
            aUK38APIYZwU6DjAkvx/FdZzaarAYqOS0+CnPvuSRQytSlXawx5qt2w6PBXWfjZ2
            Y9LoTVnf1Ay3CuSO2wPZjXlBkzqVUMhnAPstUaj6GRsUmOHq0qUsBF9LtlRglWqj
            Zwslsromw50DTV3r6ck/sv06Q/vmkNvOXR3AXWpkLZdsKYg6EyqBCLOZ0cS8uvGq
            qd4wBXHRur/gJ5bP/llFtkOScT+9D6cKC3zq25LWKyEbBpy3LtOoUkt6ZjElokVb
            ph91QWUdUUEtmgitwDsTL25vU7biM1Z8vUHdPWR7kNjKPA5fYUzQVZ34hQqqg05K
            6AXBVLCqDRpeyYhHKAuo3v6eonVJK23PWKpPRLvpfwJRZOlePzMqZCebuIAmJppl
            8dQsJYkVhFo9QR0UU5/eBu63ieVjk7DAm2/+J1wVX0cn1bAK5hgH6SEKeM8fmPg/
            nE9CwSPNlmhj5GJxvwISUvWNyMt4blO85yRe6iecU8+Fz1GUNDrcFJDnKKZxN3uh
            NplR8tlUrCdnUIk0t6b+NKk2cJW2XrkjOXvq2s/ndlW3xlToAV/slfwcYdgtSy0s
            YVzflykJBAamaIiV90qLJp1qmQCD2g2RK80lCdQD3R0TabWLVJwGAVE2mryMs/DS
            XAFUXTzWfjLoJHT8XhNrK/EAayUIZ8f9//oc0Pc/U6nf/jV4DuUQUZZ2RH38yjQA
            H9arbYwU1fCttYLdgqNNvlnvn8Bf9rfYIHYRulEM6mJ2fyBbHWvjgg4zWpQM
            =GfxT
            -----END PGP MESSAGE-----
        fp: CEBD171D5C7B1C5FB960301167AC891FB1FDF3E4
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
