apiVersion: v1
data:
    quay-token: ENC[AES256_GCM,data:zOGBYRb9Q2ws4DMvYRGs47jsD8Wwl09ucacDkJOpVjrAOROglsOtuEDly7LrDc4FFBPFuQr2rwM=,iv:WU4OsmW5s/jq+ISuaB7+O03UWBdEdpKRGDTNcHLJOww=,tag:tsV4vUxmWuYl3vDGhHI/Jg==,type:str]
    thoth-prescriptions-refresh-4cfa295278d8.json: ENC[AES256_GCM,data:xyfifyFc9ZqMG0RAk/dSQ2S4hvTM4VxjnPN/hI6hGrXxb+LXYADP0lfGFlwiUp4KSxZHe1PFd/m8eiClGUnWt7dIPw7MBPu0R/RIeMQoEpzFh2qU17A7rxTd2jxyjKR6+dM54YeEm/4fdu0Wt0jvn3ka/Cfi1cm7l7ZqeLDNqrvZqdR+QGwWslO1i3eERa67tN0ZsrzZAQzqhq28nnjblN2r0PFLAxty+Ufp3royYoCyW1UDNAU7DZ3ClO7FmqYEd77Oj8HclUbeDyFl17ENNe5LQKZVsVT3mqoRlbFXAwPq80PzC/tH6cD8mpDQ93QeeoISgDH0ws5nkEarpFRPpRS6RrfRTW21I5n3BgDozFM6DHr8JJ1AKDQhP8+94qVMBY8H9ODbyllLfXx00fMBIatgGxR0wGm0LdYQLr1MNZjX76u5AWzN+2j4TS/QVVY8lkTtVlKRQVUpOgxOF2I4L3ZMsed5lEgN3pfPsJyLLBxFtnuviAJSmxBm4ygyX3bJLug2rl1gr1m8+4WlTYSokG7mbsj3ZW0c40Axo4jvEXd97YPSBYupZhVo4WPZdWmLqjs9dRTxFx9gjwb2GjAKHerHiMXNqRdD60h4/cU4+BusGmcFJBJidTq9KQOZ8zJLy65hdi3gLYdqaIGPgUaYDIIgNY+vf2j/9oM4znhSTxrx9AYV6kXhsii1umWV68PcFryh7c4bv0QwXmHDvkfACuEbZHVi7/X0ew6w6YCYE3xz1dOwJeGlNvw1WhwPp16omYeQy6dcrGgSy1q2/xiDvgxI/3kffv2B0yjz30y1I6xMO1sJ/1Gm4SE+/aTXxCuCoos39LB5wwz2zv3lwWxKLnCHDlntPK5ajcyVKArsbER4jsdsK/6b53W1uuYy1zkKHm9/cwp0NLuVevz+WaPC9L1o5Tal9whC768wMxC8VeHxiWD5hJ1ZzsDs8DLgOR9U7tcgRqmAVb5tyIUoxAS5SHNzOV346noG2GTAkIbg3fp4nWacrvrnl0b9p5Nr4vkSk8ydxs37jkYoqERw0KuN6K3lSUN+iZKvd2+2gg2WwEzRGzDYDJSdS8Iy0knschEufO/sLkjl2m1vFN3uKuE/EFUzO4hpAuREn2m9DEFQSd0uyv2bc666/4Huea5uSCMoKjPp7Upu7ixKdW8RR7RdifcqQYsOMQs4H/IGLScRXCxvQ4NDOu4cRLzgDTcPM4mQ6JeT/9cWypmOD8+q6wmZsN1VZ3UZRCS685Or12Q2pzJOg5Wvu+OUv8DVzmn7RjxmFYklanb4DRdxQBAMVYaO2r9XNSq2wlRZbc0A1OY5k8WK+XKB8AqZSXw1el63d9X4qXdjLCj5fTNBLgG1bkMfH96+A0cc5zBM/QdTOdH7Ryx+nI7y8GPfcm1v6fG2yGfJ1yrqn0FZiOFaflo41EVvxZ82it8l1zOdOFD/tZm0CQgLLPOTcRmI77mLAXIva6Ld1roKLwFa3Mf3czF0vUY982b4n9dtDTmcTg8lsLpnnugXWtIoaiwve8jHb1/tfO8GRDaoRJdr5Zo+CkUijrgFvBZFRDr8fPk2hbEeOPnZn/LnD0+owiIRN5AXodg0KysonDklARy3xNPFySqCI2eNYL8yBZlZUMCj7X/u7gc+n4+UNeH0z9dkZqthf2UYnH+4wD++r+mDlJvcFQhhG8XjdqjPGWzj/brFzf3o43k69O1z/N5rFk4+xr1B0kEcviGdAXcj2YiOQjOeulR+fEgSyg1dCjjB4lZZ0xLJY9VuVVcJtNIwKcymOX4Bcel7NPXMXzaAahEPcEFbUyeYIkpVW1Q82Ww/eI05/riFoPTevEEOjeiEP2Gpg3aDzW3ODzUKYvsrkH02NF5eibIRDBYh2tqbwCUloYkCFL2GtdgVk9L+lbzoBzSztBkVHN9lOa0XlfMcM1GndCCAE9PcvMbvhD7zdcAeSnKdeKaFh6Kd+WbDA8bnRtARVEJUHOJCQd9nB1o+57YqO9oVQ+L3xFrg2qKr5YWuLHVuH89G8lJ0poLBsB0r8XIf/CH/sNwsdUZr8tR91zJKUAdy2igosrH55IJEv7/Wef71Nzf2i4XNiDQ5xoLUOzw27K6ChjoR5s2qOG0Us6pb/H2i2/g7IcWt6T6kNKj3WnBynZw3w8j5m4/nht7isLh3IUbPZK0DB9t7klPU5qO+IDN49fDn20sonilKM0h3QYMwTtqBPmmg6AXi64LF4J4P0zm56ADE7Sb7L/ovPlhUz1FxkEMhDeHc7BOktXLrhrS9AFFAYwPXxA0zqIlsSx2RWbVR8VjIZ493lRS3wppXaWrYRPq2BzJ35HjFzuTAL+Ct4zFvbQs3ixdpqoJTx6wYpCKGeI2tBzrWVBGt5k2/1gJHQiiJJzVb/uYBoK5H0shiMwwv7VZ+MvGksOqxRikw3BZ+fJoPPNOXU5p8dn8zpa2BhVkVF19O5+3fTN1iVtqGKQ/KSldpdK+21nkom3/IyOgohjbD4AxD7epMjng6O911dMrzOeYLrEuOZvgHro1mpuGAS5rrBqkgPFa+40V6KdCPZBp6D6vSm7DxK5KrlJXhcQxu3tpXT48Zd9Red0HlXhpIg2YT3wslzZPozeO+3neyys99X2u/A/eaUWrvoD4pBhBbftXahy1qPnyetQrxEAxO2HovhdsQXDmKt6HuWAupUrIyyOBaiFgozvuVVI2t9O4jjdJLhQA0WVks3CkQNG8K709OSPAZK3yL+w7kC9IeczQ9mlRT7AL5UdN0i9ennwVIhD9d376NS7lnQClgQZVc8viYkyoxajEVIPT7QwD1+V4YfvfNlVAFo84j7Zt0aKfY0IDssmMqV1QfmmMEEXPJOsUHNpWMomK26bCLBMNlYKAyytfUpjHRHubaLSki5OYOkEhOAW8kOBlX2Zt/oDoKa0cqbMmFFOWwh/UmlERQequbaujTx7axvO0zFwt+raYk6yoULzwj8vyv3QQDVR5SYb1OIFrAiMb/ejCaD35yhOWdX0YTqwTi5oBQdr6E94AANC5ecMcKnltfJzVGAjv0tI+iGH5p+rFyUYVpdNilFo8DT8/EHaLFUTpi6rDICKhVzCfCzisqk4/96SjcNRRvvbk0FQfZuVHmQe1ZiGH1Maxvz+qk4vPjypY116kkqXHpumpMQyyOXbnsDAJG2bGX7e2bFSfT18d5YXQ2zbsRW1srglXMeT+xlplgtrKQEtrw9olpWR5fg7w9OeiYb4RI2Xf1nrK6oJ9akxCPmJ7kWWC5r85k3pCOrYMXzI4JabDC3wAgfHmc1hhEzpzAn8eoEYCRWfDZl6OMONsy/7jwmGVJsWIqgJ1Q043n2LN6jw4Gj+Po4ZSQ5gba03eSkHdIm1l6DStRAQJhk8rOLW90SXuYvDNlckFXF2DrZHvleAxaPZxejSAhgqNpijCinrWle09yT0FsnBdVuGJXKHgJ9nAbB+1q6B9H9D2zhuUIwUWGF0WbCuvGDBx8pM181BcdoFHRTUAPTXXT7Uwu6vqVxce2bXx2Vv3jdLbVetx7SKF/wVwgHv64xIbbrfFSI1onBgc2tKCgxx/UgfyFs3SPie/Ybeq67DjZf1DtCwDutKqxjOx61QBDmBIFhp/GwpfFL+cMjbpEmQPIB2dFR1cKsJA1hp+e7AitMbBm4bqtA37RtPgw0ar9vv5+XMFbLa6oDv3m1mWOyJhs14gwWxnd1ZfHuJyxWrqtciRWVLMa+HfNCbDXk/5kXrilc/mD4znik4Xqh3H25kY3fmb1y1Sv/+FZw1g2iHNCFKlWMuOgTn0V/L4rmMtNf0AUhgpI40nFfkRy5BKVrwG+AjFYRI4FNLI51mRQZDfeUsmz9xK0P8w2/WWW1KWsYS4MsTcnh4JP34EbDGdWvDY1JxAI1pPX2n/fwrHmhI+dK7aJh6o7ViIcuXrvNpen+r4R14rj4QC6g05nksA61wpsDzdijuVdOJ8RfOl3/neZj5B8jZl8w+SlSU34fAyFDV/BukKEZg1bJvoFyb2vbEM+ojkBLwUd0oLTZFr6tehFUXlk5s7gbEt/mt2TnQT2US1pMiIlldYcIX8VqWRD2uQ4cieH3eJui/hwG12Y0zaqqZBHIaNbm+o+VohTbtRet52scbmNEtomqL+N6yEfyPoDk3TIjNhN5NdR/xfQCaUvonOyV3AvMGHu9Vhxsc9jGsW0aT2T/v2s8g7MswEO4WWnqkkETMt1gYnh8534LgFgWSiC94almxNFmv3qLr8blNInG55Zt0C+Zg==,iv:udqjxQXsIDE1RMT71kHkEGvVuSigs/M5LG7+MhmskDg=,tag:eeFdJQiYnvqlXGe//r8sFQ==,type:str]
kind: Secret
metadata:
    name: prescriptions
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-05-05T12:08:29Z'
    mac: ENC[AES256_GCM,data:ip9eFCoWnPE+D+t36SFzkJMGE7159vWvscBNdUGnchiVl0D5WXw3S0q2HNSx3wbeJN1kTgCGB9UoiqbkR1Ep2udvNsHscd2r2ETQxVMbgK9k4GYjO2cBk0L435Zxju6iPNAxiiNOIDxf2e2uegnT8CW4Y4rAYaideZZ4oyzgCD4=,iv:rrQxrHGq/2QrZ6awf4tXWLSTvT9MDJhq4noadw9zPmw=,tag:/EEVhfkYmLkgj9FVUT3vAw==,type:str]
    pgp:
    -   created_at: '2022-05-05T12:08:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYAQ//ecrlGBRphnsg1n69vXDl+b27DbFEO4qLhJ9Akn/bMVGy
            AvNzcpKDX6HNW6Bw+M3+o3t0qHpyE6F/CGV/EGtZugg1w1uApSQQLif41z19EkqH
            OSec/hsPqJ5wuOQoKB7rMxVIHDpMc6ihOkwKGN8oETBjniYsI1C9AQ2aSl23FSds
            GSnRcGkvsJaMDQJ4tqY6e4gI/TbkmqbkjZ0oiuvZRvJftUzp41e+PVKCXt2GxA2v
            98fYvGqmR/ReIwosTDruRonbzQds3/xUSPNjG/eWqABck5/XEYS5v3AEBd+UcRrP
            Zvq7nq4SlUZwVZSptSdegztcMZzKIXvr83tZJumme4qnKqXbHIEUC1KMSxdUhnen
            Fiy8WcdK8pzHMhcjEuRP7/tFAwgV6yGwyHJmx+AVTg/pwO9SIw2VEACvD+MAR/23
            f8nJGImzxwlaeGW3hM9uQXt83o90Y2yFFwv+hchmxb5K2UlwBE56XyYnyiU/spm6
            YUg0Vq+5yAO69+93o57PrxdESr9suJLPTtRLYuUOLNleKgi2AhBld8MsOzVHtx+9
            3012sdJbkz0oWX4HhjxlZXRrqES/+hDXS24hAux2cML0zX5OrT5avoB1YrL/mA6r
            IrkNQN4iBs8VzeqEF8CjLX8E5CnBihMgHWR8QdRno4Djh5ZJeKF3NideNt6XnQrS
            XgFShqWsWbxyNNnN56XUglXNwOqvkjkyw0nrYKrZI1r6BQ7AAFSkrq7uaut4GWA2
            Pp3IzuvNH4evXXBfv8ha5YCzbE2ymMAoEvBGlANsxnpOUNcpY2SnGD9nytYpmeI=
            =p7Cf
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2022-05-05T12:08:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf+MsdU51uJEZu34tE1cZONLWQNHKpCi0koePH+/tdr3J0H
            8ImWDAuAFBPVHRw/OuCWDJl7KQY+PKtjnLPUUpI/Ud7NJOS65dQLqLMR/AgSyvto
            Sum++M0kqelJR2EKxJ3Pr+UOiw6623Wmo4nWe+zOC/Kz+Aj1oL+YoUqd+inQMUCn
            paFa0rHOs06b3gG8NR/SVtv1VEcMjsaw0UKT8yKcnVMIisnj1i/wGOjZZjAxK2X5
            3jM+KLFSBJPcZ77QiTa6jJwQGXAvI4GPU1nwVhtZybnQoRhZrJSzjrPyp1KfTeMb
            yGnYmzrsgrBAWK/yKOx3NbzTvInAgYsuQaKEx8TVxNJeAV/QRHt4IHtc9Z8Cj4JJ
            V4QQBxA///wAfjo0+DwCbonjwghvQb4bs21Op87yEwboR1Bq6Yby8ifRQIfV6uk1
            gBcC7LbVmxPyugMaVTaACxUHJKoZjNwPonH1HUBiTg==
            =AOPS
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2022-05-05T12:08:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAnh02t2KyjYbfyQOUovmxlhUD0qiwqk7ktMP8jRe/iDGJ
            CgMYO28qOLC2t/FTWENT1X/s2uOCotuwwVqIFmxjee5R4hPgs5grvgg13Kwlt4qD
            5CcV9MLTCL5a65mCQHlHkUF4EwkNZedUFKkk9uO426dEDgRLOnCMhuwsWuD0bdI/
            a78T1A3ZHUNX37ZeEiHRsMqen9DGuBfNogieGEWEKjL6DwbN1KeAS6/VCXcQkGo8
            HAwSw2S2rN/+/Do2mNaIzqKBCV7eUrg2JW5wzWhJe6dAavv/83RjsOUohKdccicT
            kpK5pxU8zH3CwT3H7p1kKov2L0N1kzq8rVL93QogXdJeAUH6aVJ0lcGqsUM3QA/f
            GM7vEH4nhBS2XU/BlLjzgQOw7ICCM9lKPU00GLB3e/lcgxMYhkH0g1Ox3hva5TKE
            Yveo4lY0fz7KG/mp6kTMMI83hDS2NStWUNLIPf2gjw==
            =eMxy
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2022-05-05T12:08:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiARAAsso5Fvk17E/amWoF52BHvb3FDQ3rO03K6DamOljjimwO
            AhkaD/372tVWIxVXNsQbuWMhiiKcPoFb6VxG8hdWJEM/AUPKUKzUaCx+hwmWGNZR
            ZOlNmjogiz3tDwJBGqoGowqi9GU0E2X1ItxpPLl6xjoJwX1EgVwBaO557SDGhnS+
            oAJMY8cfx6K3edKxiZw9LpzL+7MCxDhAm00Jwyku/L3QED1oOcPiJftXPChcYc7G
            T0TdOERlXJ8d1MX9JjVe1mO26wVMBSMJFqzS73RRqe33UEw0Dch2etCOMzzmyxNk
            m/9yx0rBOSyWLRlVFQBVo9j0AQiI1I9exqNHTEcJ+5fG68xuWJOpwKkhrVJ09J82
            SQKyIExoHK4DzDpAyLA8tV3P/MyB38ryPMJ+lKAucbOIaSxKZAr0RXGWCzyxPsRd
            ByPbPgHRgEB5Gom62M5gn+S8G2aqiSyvtPb7lhW90d3F8V07bfT5g0mAqYKWmhow
            Sfe4j0MD+cIC3j8nbzRrtB4cIwfYlAmh+bBanIJ8vJ8SmCJvOSe1YdR4FSoHeNAs
            PVSxGUiEgNbIM8lQx/etEZ4Da5xtzkI3xBtjdEDp1YgtXNFoxlolIlfXndODhoE1
            V/8jGtg5XUc0HZ57Xk3OAFO0kI8YoiKJKV7oOEV+DDuh+Ob4qRd95X9Zzj4WWinS
            XgHwW5Alb1/aZ4JSQIvBj9S8KSZVTKlUaInqG5rjCUNtxTPleUf3Diqfdpkghffr
            kvHYXm2r3a45GVgPwoe7MH41BBDW4+RxnYKJQB2PP9aEl9LSsDnxVteoMVrmFO0=
            =C0U2
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    -   created_at: '2022-05-05T12:08:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIOA9LRbhPydJmLEAf8Di8+8lV4KJxoG1XDrUamvmDG73373De3SGGPrC0EhzyA
            hKyDcQa5jSsAfKfr5r/S8csM5uLm9YAvHtncNe48h4itUQrv8yauPPojOAdMnLZH
            SXOAnR82F07w9TemL/34A+bUUOEh/Eg+u9MN3Fl3BGQlliOyUPIKHKN8DMyshzAh
            2EzXP+nSxc6DwhhnoMOUnHR2xKxfRq17TYeJ533N7Qz/aVA/BQMW/cif3diAsJG/
            58Zi2vLLplFx5+aPKm6bfQ7KR3dG4JXiRlPvzpuRDRi0MM3DItO2SG5AHG8vlAqX
            sJx9OPSziVVdQfKeFblpmmF/X101briaHyT3BttGBwf/Vo/daLPKmdIr5SUB6fec
            r23yT+z0Vs5ku4IFP9UWPUz6q/wgpnwAolfRqnVoZtcq5ROqaKGU1zJvujPTLSEE
            vlniHmp8GOI4dsBSuBx65PZGtBedugOvr3ZFaes9fYy2BDHb4mXBHYW3liUlihpq
            WlrFf2Csc1K4YkZyU4wG82WstdQU/IUd5zcBIwjvHsJTPq4fA/qf4LUR/A+f0hff
            9VE+GVYEVZdm8nq0QUZYnFcJ85GK5b1ixp7yRbw9SF1OeOQaFRleYwXcO+C3DvqD
            /KiGbaeGKp3SLKffktQ+2+8uALLRPmLcyIc/Xj2FGFoXReVfDEl2i9zjoSmCnvNH
            h9JeAZoA+hQKRdzugV+Jx8aab2PyVKeE9RDoBXaZKntN2FHCdwhQWUIArImH1ze5
            FwcNL9wtpDG3olDWeF4kb7SrxN+VlWWI6nzFH1ATrz6rmu/QQYPmN1TVGRJSfidA
            3w==
            =uQ/L
            -----END PGP MESSAGE-----
        fp: 8D191B7544E9CCC3547B25A877E5A5B31D13A647
    -   created_at: '2022-05-05T12:08:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9NBwWNwg7uAAQ/+PplpQRrcJq8uYEPj94HaWVuv/aehiqmCPULGuB8M1Hi6
            B7/YFRgisdn2mcDHSmCgZDnUj9xhEfn1PS+4C4QUJMfkL6m2o6ghSm+jdEQnpvo6
            3bdK2RTyivKdbmz/4+aGve/fnTuKRE6pN3y4i/SibUDtvvuZwZMQYBz8ZLaMCO3x
            MHWiBzXBY88pJsOmL7jkSBmqBbi6Tsg6z+r7eLK9RuUwPoWXiKLVsRTRgiyW2uh0
            vUrLcr7shdLFRPZo7iYv2wrA0x+WGPl1fW1TV0AGxauGz3ejcsdQBu1ByJBk9NLy
            SjBHwz44jYppTgIltcLiCmJlOlx+6OwV+QEyW31ChRLz3leIwh4zA5HWHSWx6l7p
            Vvw04edTsXbf/BszVS64fT+MVfIKHAY4866+xWg0SgQqxLn9c+/tZ8F5srqhCO0l
            PzUe5Yt1+Yav/j99/t+pXpJzOffKScyV1kCDgu3ZQjdiHTSIgOLxxZR0w+M2p+2B
            uC9VFPdVO1AaMBw0Nemi9WcYJ5wvdoipqD+isj+VIJq35iIwF7/ZjApipNVdu33R
            lL6c7Xj8aqsy5Iev1sIN2g5w73kbt2UppVzKTIfaYCf4dOYbMzmNGDTDwA/GySQP
            ovinewDE+uBTrMXl88HAsVfm4BmI+bh25TP9pJftwKMavYEF405GnTMsfM818b3S
            XgF+ZBeJDMAYAtW1wDu7s8yFT6ZlPCNvuxY81L8lV8xwcxqYUCQ0dLtBxzHlRWO8
            xT7OlY43LCpxVuyIoZfcwZYuhxma81vCnkIQ91TSTRyPfEN4K2OLkf5Q7FMKoCk=
            =xfN7
            -----END PGP MESSAGE-----
        fp: A01778ACB7CC4D41B00FDD78CCBE624D8FF6D016
    -   created_at: '2022-05-05T12:08:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxdcElc1DYwyARAAsHvY1LAgPtN+1e2c0HxEwLSj15y8Tgt4C9nmZhG3The8
            p/hmQyArEDdowan4zCYckAn3zUW+8EjCgIe7BaFVG0Gi9Bx9vQnQm4smi9o1Q22Y
            PwPvxnZawuBVTn+8cSXc1wS1tYCYUiwhHcZdb4s+vCjADfSqDmKit78bMY2xup34
            xUrfGT3BJRwuKil8FlEN9bGpXH6Rfm5CwCRXEnyvyczMu8WAOrWjbBtQzQzrN2+C
            DZu5ESR2MV65CqhfhYtAlC7uFpeSv16kgUm0f4EbTAenpCrUlzbyuSR1U4GxFRwv
            JOsKuJByCDyRLVe8+WnryCaqwkdJ3oyqeycMxn8Cr+sRg3UIu4o/1OnllXgSu2of
            KuLlRSaUKdI4UYSaKBmJi5szWfKi9+LIXeulkbCB02po+Wkx52VFlgqalXqgEDi2
            MTdWtTUKijytQe/IBDHG3Bics9ik6IWH8+kK2z3UhwXvegLSor2ONmB/5WprT25G
            DZu6OcBcr4VR14q2qDUUmQ1kU/wZF0Wsbw+QhZhxRwIvgJMBFpMn1si6vEF1lZT4
            YpS361+BapzfBbdFX2faueBRBEcbyEsPlsTkvcDL1LhmjDV3D2XjsIliqQ4PGtn3
            QiCOdaYv6XITuznp1/RwwqTGluXPzO2CFWlJMZvbyyixUH5uPP7v/beQx1wY5+3S
            XgHe4sey8t7tOleA0o0WsxdflVkPN72+IxlFghlBfrvjv+Xe8CHfc5btWoJVKa8W
            6f7GqSTYULvdPu0RoCvWhbweosvu3P3UWubYn4Q3j4fvYblgzp5tqEgZgEeozaw=
            =3gtO
            -----END PGP MESSAGE-----
        fp: CEBD171D5C7B1C5FB960301167AC891FB1FDF3E4
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
