apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: purge
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - imagestreamtag.yaml
patches:
  - path: put-into-infra-namespace.yaml
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: purge
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-backend-prod/workflow-helpers:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: create-purge-issues
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-backend-prod/purge-job:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: purge
