---
kind: ConfigMap
apiVersion: v1
metadata:
  name: amun
data:
  amun-api-url: http://amun-api.thoth-amun-api-prod.svc
  deployment-name: smaug-prod
  infra-namespace: thoth-amun-inspection-prod
  inspection-namespace: thoth-amun-inspection-prod
  logging-no-json: "0"
  postgresql-host: pgbouncer.thoth-graph-prod.svc
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  bucket-name: "thoth"
  bucket-prefix: "data"
  host: "https://s3-openshift-storage.apps.smaug.na.operate-first.cloud"
  endpoint: "https://s3-openshift-storage.apps.smaug.na.operate-first.cloud"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  pushgateway-host: thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud
  pushgateway-port: "80"
  pushgateway-url: thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud:80
