apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - role_bindings.yaml
  - thoth-notification.yaml
patchesStrategicMerge:
  - imagestreamtag.yaml
patches:
  - path: resources_patch.yaml
    target:
      group: apps.openshift.io
      version: v1
      kind: DeploymentConfig
      name: metrics-exporter
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
