apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nepthys
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/thoth-station/nepthys:pr-95
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
