apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: adviser
  app.kubernetes.io/managed-by: aicoe-thoth-devops
resources:
  - argo-workflows/thoth-repo-init.yaml
  - openshift-templates/thoth-repo-init.yaml
  - imagestream.yaml
