apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: init-job
  app.kubernetes.io/managed-by: kustomize-ksops
resources:
  - argo-workflows/initialize-schema.yaml
  - argo-workflows/register-indexes-template.yaml
  - argo-workflows/solve-core-packages.yaml
  - argo-workflows/solve-data-science-packages.yaml
  - imagestream.yaml
  - role_binding.yaml
  - role.yaml
  - serviceaccount.yaml
