apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: init-job
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups: ["template.openshift.io"]
    resources:
      - "templates"
      - "processedtemplates"
    verbs:
      - "get"
      - "list"
  - apiGroups: ["template.openshift.io"]
    resources:
      - "templates"
      - "processedtemplates"
    verbs:
      - "create"
      - "delete"
      - "watch"
