---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: init-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: init-job
subjects:
  - kind: ServiceAccount
    name: init-job
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: init-job-argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-role
subjects:
  - kind: ServiceAccount
    name: init-job
