apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deploymentconfig.yaml
  - imagestream.yaml
  - route.yaml
  - service.yaml
commonLabels:
  app: thoth
  component: advise-reporter
