---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: metrics-exporter
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/thoth-station/metrics-exporter:0.8.2-dev.5"
      importPolicy: {}
      referencePolicy:
        type: Local
