apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - thoth-notification.yaml
images:
  - name: advise-reporter
    newName: image-registry.openshift-image-registry.svc:5000/thoth-infra-prod/advise-reporter
    newTag: latest
patchesStrategicMerge:
  - imagestreamtag.yaml
  - cronjob.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-prod"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
