---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ultrahook
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: qeb-hwt-webhook-receiver
spec:
  lookupPolicy:
    local: true
