apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deploymentconfig.yaml
  - imagestream.yaml
  - route.yaml
  - service.yaml
  - argo-workflows/qeb-hwt-integration.yaml
  - openshift-templates/qeb-hwt.yaml
commonLabels:
  app: thoth
  component: qeb-hwt
