---
kind: Service
apiVersion: v1
metadata:
  name: qeb-hwt-webhook-receiver
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: qeb-hwt
    component: webhook-recevier
