---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: amun-api
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: amun-inspect-hwinfo
spec:
  lookupPolicy:
    local: true
