---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thoth
    component: result-api
  name: result-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    service: result-api
