---
apiVersion: v1
kind: Service
metadata:
  name: result-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    service: result-api
    app.kubernetes.io/name: thoth
    app.kubernetes.io/component: result-api
    app.kubernetes.io/managed-by: aicoe-thoth-devops-argocd
