apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/version: "0.6"
resources:
  - ../../base
  - role-binding.yaml
  - thoth-notification.yaml
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
