apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/version: "0.6"
images:
  - name: mi-scheduler
    newName: image-registry.openshift-image-registry.svc:5000/thoth-infra-stage/mi-scheduler
    newTag: latest
resources:
  - ../../base
  - role-binding.yaml
  - thoth-notification.yaml
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - patch: |-
      - op: replace
        path: /spec/templates/1/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-middletier-stage/mi:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      annotationSelector: "operation=mi"
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
