apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - configmap.yaml
  - cronjob.yaml
  - imagestreamtag.yaml
generators:
  - ./secret-generator.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
