apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/version: "0.7.0"
resources:
  - ../../base
  - ../../base/argo-workflows/kebechet.yaml
  - ../../base/openshift-template/kebechet.yaml
  - thoth-notification.yaml
patchesStrategicMerge:
  - configmap.yaml
  - imagestreamtag.yaml
patchesJson6902:
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-succeeded-
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-failed-
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: kebechet
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
