apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pcache.yaml
patchesStrategicMerge:
  - imagestreamtags.yaml
configMapGenerator:
  - name: config
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - secret-generator.yaml
