apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - postgresql-ephemeral.yaml
  - argo-namespace-install.yaml
  - argo-ui-route.yaml
  - thoth-notification.yaml
patchesStrategicMerge:
  - configmaps.yaml
patchesJson6902:
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
