apiVersion: v1
data:
    GITHUB_USERNAME: ENC[AES256_GCM,data:G4bPyG9OjfzGFaKd,iv:hm/usfZCkalspv9U8FlTORa+CdFSm5HI0Z4w9fke/B4=,tag:ngIYOYekjAtpLAtqf1MdvQ==,type:str]
    GITHUB_PASSWORD: ENC[AES256_GCM,data:l/zhhmJV7o86h1ea28YJXA==,iv:Jw3VybABgkOa49DU7Ie8L9k8838rGlBjhac1YtzXZEk=,tag:itaSqK8KjRcQoZeQtQUa7g==,type:str]
    GITHUB_ACCESS_TOKEN: ENC[AES256_GCM,data:8ORxRBhEL01FR/IohziZo1gE50GrjQCm8evFqroWwJ8ANvJyYemvaw==,iv:EG1cBeAv3YF6oomjcyjaCKUppBjAod6r8g13eafXqwQ=,tag:fWFajjYUA/7EiNtojHPIoQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: meta-informa
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-07-24T13:05:15Z'
    mac: ENC[AES256_GCM,data:9xIAvVx3+yDk1GzOtm7JOzvDGuQkgtXp41rBFtXJ8JOVy1k22o19IgRDgc2kB5B94K6EUDBEM3WAzbEy3ddhTiXGnJRjsLvk/Cdo/+SCNWRRrwutlb1/M6pHirfH1RfSOsA09AtAk2/Iu+TFH8oV6x4P1LrOA7+zQLK6HlWcnY4=,iv:uHEqTfVDLLSdX8tgzsZLCcoy1rIubQmw5jDhM9CBT+I=,tag:i2oD9ElnpCUgFCIfDm21Kg==,type:str]
    pgp:
    -   created_at: '2021-07-24T13:05:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYARAAoogUCSuQtAIPd+aD0QEg6CPhGPr2mbJr9HY27QYfNxEH
            v2RhqdrQnzs2+mmavGukvAp5Ts12VSQsHzZu5EIPEWVGECtgj0Cu3jMnUr+jYtk6
            fFNx8uApsT8ZLjWCUyKhgR3cYPhhROHT5zLenlnwXmWC0f3NP+YBN2vrInNrvTP0
            TR6q8Hyh5+osW9UPZHIJUmzqHpoBZj2Iggq0gzG3xSW6T7oGNQLi/eJ0IO4CaSmx
            9N1Q16rruYRyK83PLalREJDjO62+AmFOzPvufvDgRU6PmJsvwl+1p9ekRFqEtBt3
            rIO749wZrm5yEzU7Ql+uZv+c+mkX80IGmv0Kl+wqEdMu8znGUh/tIJVoNFJyWIaM
            RRG3hLnpadZ6tEP8DtoKLCBd7RNDYu9ZZ7SrP6ZEQ6Z5i98LpHwCyA/wwJJfSzvl
            DlKKnP2pN9oHqTWiff5IbWGenUc0a+5omm1uDdJ0XKoUO2rXNTJB0Wq6IruO4t/5
            dwaRQM+kTenpxOqPo6wKq6S6hNmGFjvYymERC5Brh5F3zM3A5p5fpiMKkCofK693
            oWsUWfBO7QRIwshZR/BrXT1fXqlAs61nFFa24Jn6Otmt/+6EcGJjUfk5yhBi57ep
            /PqmcqmCHE3m3V9RqG8OP8KdwLnNGdwYhlz19jX02uzYzodtk+NlJuuRBDXrT5fS
            XgE/ZnuRHQ544ycGE9r0SuSTmygg+yDjTv6ixugPJ8/CgWD5ncrT+8ym7dEaUrSo
            A0CNVyr6BtwBQcTj9p03t0c4DrXvypPHe81vBfBv2bRcSsA4+jJ+7scapxOLHx8=
            =mCAs
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-07-24T13:05:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQgAhwLrAMYINIVl9nV/k1Gx+Gi9QJP+WV7Xg2Gd439n6FY5
            78iPB9fmJPyXLAiYnYUH3P58OFOCxJXTN5qvTGZMDEoZFmNE8HVNonj3JWEkzSPD
            TtaXWPDSj6wa0R3KN28W4e9GyLrM7EZbiJnacwdNV9XGPdv2yxIwP5DZPxmHAh9b
            8fLJRqAROcsB+0ZLJEqtWNCxjL+cy6ltohxOOhl9zNVBagkxSZd9KFtJz9d3PGKn
            bKhcz/7SUqMVMkGtgqyNunyQmoMqj0V6UZSLWGTbDC7A9lPfiex1Y53ex2+w8cK/
            Fwfl1HF0FnNwMpZzC8eJvD8eq8cqWftQ6hYnOE1o49JeATSF9ieKx0NtMOjYgtCD
            +KWTelgGGDH8TYd/fl4T/eKFPlBJjE3tMTXeAobwk92NFyc+Idu/Rop1LhKEvdan
            pIFbYBw1E36bAywNTdAxg35Bvrl6Ngy+uzRc2ffy4w==
            =HGJH
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-07-24T13:05:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAhcYOfxQ5ftMiitHEGfYRzm6Clb3bd1mjqld5H4+pGl/6
            ZZbQaBrOGVB5rZFTt73LshoV8zbIrpBbwmtL9wpA7ugXA5d/XGL4cyV4UcI1lkhM
            XAS2qJH5vul+l8n3fX5BozxRN+9YZ7E0ontcVp2UD8s9O+5IFuW4YRG/z3yWmylA
            1eXwwVnichvpZOayAz0wLF7PYXZdDX8IVe9hu+bG8ilQOqmFqqBXRk1lck62Csi6
            2vhwWN7pP+1F2eaoyfyhIgyGue6kAEbuFVQUu7E9O13uTXnP8XbFX9S5/S0aGAml
            caj6PI/lt2/OqDNafSjNzlmE5R8ctMpSM6ZwrrQ7PdJeAQzPZUah/MeVFlIwPQsQ
            4uvLrP3TyN4nd7EKN+FhCNUi+Y0Sv9nxhEK4sdSzZLrRLpakd8yJRGM5HlRAEtT4
            lNjn1sEC1Uhfx+93ntkoMyC2l55StlBQPmICStWPiQ==
            =yJz/
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-07-24T13:05:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//cLvkIa5SMdG+eYaR/yAFGuuAeTP3o04gBavKXGPRa1G8
            AscxW1rsKaW2FDi6/qjHn0VrobB3ZeXQwYL0RI8AxmSFZ/Sgg/EFucJnr6pt15xb
            Bal4Re9UdXtO3eUq/0DgapmYe8QNpC5m13kvXp/J7r5nExvkMD8JJtzDXUxg6Y79
            Kgb9fqSjwU5qTjj4QnOMiAg2A1TTwhHh9Ip0lWqrn8wnCjgFrf85FHUb70Ki+N7M
            33X/ahwIQTr/o07YXVMrTg+x6Qo5GdLKYsvhvevk2reKJQujcW/0VQOa7epL/Qpx
            9kkK9cna8hqHTx+/HMVig2oZdcQw8Wf8CarkaGIX4l8IB152YjAUuldxFg6l5zuF
            WutmXpGpjqSBL5GtyWlT0IdTSllzbnASUynLPhsj8EUOVz2qz1u0iRJ1iS3zR8qk
            jF2HOvwk2d4/wH+1dURSy48mIRCKUpB7wYdAHutY6ah4LeP+ghQwKMhXCdb1yynJ
            ZxwS1UdsOD7kR0YB4FDoY0grFMMqFONZN0ACHOLsrt6fQDp24HVmRFqb2yd92ivQ
            pqPaUIlVj3kgJAizI207dFXZhQ5o7tEpfvMCaohdDYuwktbr0p51LOn/xhf82FF/
            rbN17JDYFVhvGzZiF2k8gW6SkdJ46oE6WL48aSpJ0/nJJ54kGK87rUgiv84ERNLS
            XgHwskWLDEf5BWVl8BfriJdDr/ES0SYbBBYDzOgwXL8NceyI/66CIZeiFSKZtVhC
            NDackGZ7+DHlvC2icOxqbpZIN9FFM0EbS9PQdsHAW1n2nMZpKbyFJ5fdlofyeC4=
            =eoVG
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
---
apiVersion: v1
data:
    github-access-token: ENC[AES256_GCM,data:7wSlqoZ5Hu94+Qdx/64aS5vA6vTOTX46WbLivGi0MClhZ2R2DKAqEldTR/Py/p7bL5Tk3VCmf8I=,iv:GFYbZs+XTfZRAL9vuC6YT37B7kWBAh5WEvniFFkVqys=,tag:SGYWNSweLQeKTmvn0xXZ8A==,type:str]
kind: Secret
metadata:
    name: sesheta-srcops
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-07-24T13:05:15Z'
    mac: ENC[AES256_GCM,data:9xIAvVx3+yDk1GzOtm7JOzvDGuQkgtXp41rBFtXJ8JOVy1k22o19IgRDgc2kB5B94K6EUDBEM3WAzbEy3ddhTiXGnJRjsLvk/Cdo/+SCNWRRrwutlb1/M6pHirfH1RfSOsA09AtAk2/Iu+TFH8oV6x4P1LrOA7+zQLK6HlWcnY4=,iv:uHEqTfVDLLSdX8tgzsZLCcoy1rIubQmw5jDhM9CBT+I=,tag:i2oD9ElnpCUgFCIfDm21Kg==,type:str]
    pgp:
    -   created_at: '2021-07-24T13:05:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1gbAjViyxWYARAAoogUCSuQtAIPd+aD0QEg6CPhGPr2mbJr9HY27QYfNxEH
            v2RhqdrQnzs2+mmavGukvAp5Ts12VSQsHzZu5EIPEWVGECtgj0Cu3jMnUr+jYtk6
            fFNx8uApsT8ZLjWCUyKhgR3cYPhhROHT5zLenlnwXmWC0f3NP+YBN2vrInNrvTP0
            TR6q8Hyh5+osW9UPZHIJUmzqHpoBZj2Iggq0gzG3xSW6T7oGNQLi/eJ0IO4CaSmx
            9N1Q16rruYRyK83PLalREJDjO62+AmFOzPvufvDgRU6PmJsvwl+1p9ekRFqEtBt3
            rIO749wZrm5yEzU7Ql+uZv+c+mkX80IGmv0Kl+wqEdMu8znGUh/tIJVoNFJyWIaM
            RRG3hLnpadZ6tEP8DtoKLCBd7RNDYu9ZZ7SrP6ZEQ6Z5i98LpHwCyA/wwJJfSzvl
            DlKKnP2pN9oHqTWiff5IbWGenUc0a+5omm1uDdJ0XKoUO2rXNTJB0Wq6IruO4t/5
            dwaRQM+kTenpxOqPo6wKq6S6hNmGFjvYymERC5Brh5F3zM3A5p5fpiMKkCofK693
            oWsUWfBO7QRIwshZR/BrXT1fXqlAs61nFFa24Jn6Otmt/+6EcGJjUfk5yhBi57ep
            /PqmcqmCHE3m3V9RqG8OP8KdwLnNGdwYhlz19jX02uzYzodtk+NlJuuRBDXrT5fS
            XgE/ZnuRHQ544ycGE9r0SuSTmygg+yDjTv6ixugPJ8/CgWD5ncrT+8ym7dEaUrSo
            A0CNVyr6BtwBQcTj9p03t0c4DrXvypPHe81vBfBv2bRcSsA4+jJ+7scapxOLHx8=
            =mCAs
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-07-24T13:05:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQgAhwLrAMYINIVl9nV/k1Gx+Gi9QJP+WV7Xg2Gd439n6FY5
            78iPB9fmJPyXLAiYnYUH3P58OFOCxJXTN5qvTGZMDEoZFmNE8HVNonj3JWEkzSPD
            TtaXWPDSj6wa0R3KN28W4e9GyLrM7EZbiJnacwdNV9XGPdv2yxIwP5DZPxmHAh9b
            8fLJRqAROcsB+0ZLJEqtWNCxjL+cy6ltohxOOhl9zNVBagkxSZd9KFtJz9d3PGKn
            bKhcz/7SUqMVMkGtgqyNunyQmoMqj0V6UZSLWGTbDC7A9lPfiex1Y53ex2+w8cK/
            Fwfl1HF0FnNwMpZzC8eJvD8eq8cqWftQ6hYnOE1o49JeATSF9ieKx0NtMOjYgtCD
            +KWTelgGGDH8TYd/fl4T/eKFPlBJjE3tMTXeAobwk92NFyc+Idu/Rop1LhKEvdan
            pIFbYBw1E36bAywNTdAxg35Bvrl6Ngy+uzRc2ffy4w==
            =HGJH
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    -   created_at: '2021-07-24T13:05:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAhcYOfxQ5ftMiitHEGfYRzm6Clb3bd1mjqld5H4+pGl/6
            ZZbQaBrOGVB5rZFTt73LshoV8zbIrpBbwmtL9wpA7ugXA5d/XGL4cyV4UcI1lkhM
            XAS2qJH5vul+l8n3fX5BozxRN+9YZ7E0ontcVp2UD8s9O+5IFuW4YRG/z3yWmylA
            1eXwwVnichvpZOayAz0wLF7PYXZdDX8IVe9hu+bG8ilQOqmFqqBXRk1lck62Csi6
            2vhwWN7pP+1F2eaoyfyhIgyGue6kAEbuFVQUu7E9O13uTXnP8XbFX9S5/S0aGAml
            caj6PI/lt2/OqDNafSjNzlmE5R8ctMpSM6ZwrrQ7PdJeAQzPZUah/MeVFlIwPQsQ
            4uvLrP3TyN4nd7EKN+FhCNUi+Y0Sv9nxhEK4sdSzZLrRLpakd8yJRGM5HlRAEtT4
            lNjn1sEC1Uhfx+93ntkoMyC2l55StlBQPmICStWPiQ==
            =yJz/
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2021-07-24T13:05:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//cLvkIa5SMdG+eYaR/yAFGuuAeTP3o04gBavKXGPRa1G8
            AscxW1rsKaW2FDi6/qjHn0VrobB3ZeXQwYL0RI8AxmSFZ/Sgg/EFucJnr6pt15xb
            Bal4Re9UdXtO3eUq/0DgapmYe8QNpC5m13kvXp/J7r5nExvkMD8JJtzDXUxg6Y79
            Kgb9fqSjwU5qTjj4QnOMiAg2A1TTwhHh9Ip0lWqrn8wnCjgFrf85FHUb70Ki+N7M
            33X/ahwIQTr/o07YXVMrTg+x6Qo5GdLKYsvhvevk2reKJQujcW/0VQOa7epL/Qpx
            9kkK9cna8hqHTx+/HMVig2oZdcQw8Wf8CarkaGIX4l8IB152YjAUuldxFg6l5zuF
            WutmXpGpjqSBL5GtyWlT0IdTSllzbnASUynLPhsj8EUOVz2qz1u0iRJ1iS3zR8qk
            jF2HOvwk2d4/wH+1dURSy48mIRCKUpB7wYdAHutY6ah4LeP+ghQwKMhXCdb1yynJ
            ZxwS1UdsOD7kR0YB4FDoY0grFMMqFONZN0ACHOLsrt6fQDp24HVmRFqb2yd92ivQ
            pqPaUIlVj3kgJAizI207dFXZhQ5o7tEpfvMCaohdDYuwktbr0p51LOn/xhf82FF/
            rbN17JDYFVhvGzZiF2k8gW6SkdJ46oE6WL48aSpJ0/nJJ54kGK87rUgiv84ERNLS
            XgHwskWLDEf5BWVl8BfriJdDr/ES0SYbBBYDzOgwXL8NceyI/66CIZeiFSKZtVhC
            NDackGZ7+DHlvC2icOxqbpZIN9FFM0EbS9PQdsHAW1n2nMZpKbyFJ5fdlofyeC4=
            =eoVG
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.5.0
