apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: config
    files:
      - config.yaml
  - name: plugins
    files:
      - plugins.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - secret-generator.yaml
