---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ci-prow-artifacts-s3
spec:
  generateBucketName: ci-prow-artifacts-
  storageClassName: openshift-storage.noobaa.io
  additionalConfig:
    maxSize: "10G"
