apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sync-job
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/sync-job:v0.2.4
      importPolicy: {}
